import Link from "next/link";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { getHostContext } from "@/lib/host-access";
import { Workspace, Panel, HostNav } from "@/components/marketplace/workspace";
export default async function HostPage() {
  const session = await auth();
  const context = session?.user ? await getHostContext(session.user.id) : null;
  if (!context) return <Workspace eyebrow="Your business, on the road" title="Become a Rent A 4Wheel host" description="Build your fleet, prepare every pickup and keep your rental operations in one place."><Panel title="Start with your business"><p className="mb-6 text-silver">Submit your business profile for review. Listings stay unavailable until the required documents, agreements and approvals are complete.</p><Link className="inline-block rounded-lg bg-gold px-5 py-3 font-semibold text-black" href="/host/profile">Start host application</Link></Panel></Workspace>;
  const [host, vehicles, active, upcoming, returns, attention] = await Promise.all([
    prisma.hostProfile.findUniqueOrThrow({ where: { id: context.hostId } }),
    prisma.vehicle.count({ where: { hostId: context.hostId } }),
    prisma.reservation.count({ where: { vehicle: { hostId: context.hostId }, status: { in: ["ACTIVE", "RETURN_IN_PROGRESS"] } } }),
    prisma.reservation.findMany({ where: { vehicle: { hostId: context.hostId }, status: { in: ["CONFIRMED", "DOCUMENTS_REQUIRED", "READY_FOR_CHECK_IN", "CHECK_IN_PROGRESS", "READY_TO_START"] } }, include: { vehicle: true }, orderBy: { pickupAt: "asc" }, take: 8 }),
    prisma.reservation.findMany({where:{vehicle:{hostId:context.hostId},status:{in:["ACTIVE","RETURN_IN_PROGRESS"]}},include:{vehicle:true},orderBy:{returnAt:"asc"},take:8}),
    prisma.vehicle.findMany({where:{hostId:context.hostId,OR:[{status:{not:"ACTIVE"}},{listingApproval:{not:"APPROVED"}}]},select:{id:true,make:true,model:true,status:true,listingApproval:true},take:8}),
  ]);
  return <Workspace eyebrow="Host workspace" title={host.businessName || host.legalName} description={`Application: ${host.onboardingStatus.replaceAll("_", " ")}. Your access: ${context.role.toLowerCase()}.`}><HostNav /><Panel title="Next actions"><div className="grid gap-4 sm:grid-cols-2"><div><h3 className="font-semibold">Returns and inspections</h3>{returns.length?returns.map(r=><Link key={r.id} className="mt-2 block min-h-11 rounded-lg border border-white/10 p-3 text-silver" href={`/host/reservations/${r.id}`}>{r.vehicle.make} {r.vehicle.model} · {r.status==="RETURN_IN_PROGRESS"?"Inspection pending":"Return due"}<span className="mt-1 block text-sm">{r.returnAt.toLocaleString("en-US",{timeZone:r.bookingTimezone})} ({r.bookingTimezone})</span></Link>):<p className="mt-2 text-muted">No active returns to prepare.</p>}</div><div><h3 className="font-semibold">Vehicles needing attention</h3>{attention.length?attention.map(v=><Link key={v.id} className="mt-2 block min-h-11 rounded-lg border border-white/10 p-3 text-silver" href={`/host/vehicles/${v.id}`}>{v.make} {v.model}<span className="mt-1 block text-sm">{v.status.replaceAll("_"," ")} · Listing {v.listingApproval.toLowerCase()}</span></Link>):<p className="mt-2 text-muted">No unavailable or unapproved vehicles in this queue.</p>}</div></div><div className="mt-5 flex flex-wrap gap-4">{[["/host/profile","Application & documents"],["/connect","Messages"],["/connect?view=cases","Claims & support"],["/finance","Earnings & payout status"]].map(([href,label])=><Link key={href} className="inline-flex min-h-11 items-center underline" href={href}>{label}</Link>)}</div><p className="mt-3 text-sm text-muted">Payout availability depends on current financial approval and release controls. A displayed balance does not mean a payout is enabled.</p></Panel><div className="grid gap-4 sm:grid-cols-3">{[["Vehicles", vehicles], ["Active rentals", active], ["Upcoming pickups", upcoming.length]].map(([name, value]) => <Panel key={name} title={String(name)}><p className="text-4xl text-gold-bright">{value}</p></Panel>)}</div><Panel title="Prepare for pickup">{upcoming.length ? <div className="divide-y divide-white/10">{upcoming.map(r => <Link className="flex flex-wrap justify-between gap-3 py-4 text-silver hover:text-gold-bright" href={`/host/reservations/${r.id}`} key={r.id}><span>{r.vehicle.make} {r.vehicle.model} · {r.confirmationNumber}</span><span>{r.pickupAt.toLocaleDateString("en-US", { timeZone: r.bookingTimezone })}</span></Link>)}</div> : <p className="text-silver">No upcoming pickups. Approved, available listings can accept reservations.</p>}</Panel></Workspace>;
}
