// Generated by scripts/generate-mobile-contract.ts. Do not edit.
export interface MobileOperations {
  "requestPhoneCode": { input: { params?: never; body: { "phone": string; "deviceId": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "accepted": true; "challengeId": string; "retryAfterSeconds": number } };
  "phoneSignIn": { input: { params?: never; body: { "challengeId": string; "code": string; "deviceId": string; "platform": "IOS" | "ANDROID"; "appVersion": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "tokenType": "Bearer"; "accessToken": string; "refreshToken": string; "accessExpiresAt": string; "refreshExpiresAt": string; "sessionId": string } };
  "requestIdentityCode": { input: { params?: never; body: { "purpose": "LINK_PHONE" | "CURRENT_PHONE" | "CHANGE_PHONE" | "RECOVERY" | "LINK_EMAIL"; "target": string; "proofId"?: string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "accepted": true; "challengeId": string; "retryAfterSeconds": number } };
  "verifyIdentityCode": { input: { params?: never; body: { "challengeId": string; "code": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "outcome": "LINKED" | "PROVED" | "REVIEW_REQUIRED"; "proofId": string | null; "requiresSignIn": boolean; "recoveryId": string | null } };
  "loginMethods": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "phoneLinked": boolean; "phoneLabel": string | null; "emailLinked": boolean; "email": string | null; "recoveryId": string | null } };
  "requestCode": { input: { params?: never; body: { "email": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "accepted": true } };
  "signIn": { input: { params?: never; body: { "email": string; "code": string; "deviceId": string; "platform": "IOS" | "ANDROID"; "appVersion": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "tokenType": "Bearer"; "accessToken": string; "refreshToken": string; "accessExpiresAt": string; "refreshExpiresAt": string; "sessionId": string } };
  "refresh": { input: { params?: never; body: { "refreshToken": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "tokenType": "Bearer"; "accessToken": string; "refreshToken": string; "accessExpiresAt": string; "refreshExpiresAt": string; "sessionId": string } };
  "logout": { input: { params?: never; body: Record<string, never>; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "revoked": true } };
  "logoutAll": { input: { params?: never; body: Record<string, never>; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "revoked": true } };
  "revokeDevice": { input: { params?: never; body: { "sessionId": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "revoked": true } };
  "devices": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "devices": Array<{ "id": string; "platform": string; "appVersion": string; "lastUsedAt": string; "expiresAt": string }> } };
  "me": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "role": "CUSTOMER" | "HOST" | "HOST_EMPLOYEE" } };
  "vehicles": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "slug": string; "year": number; "make": string; "model": string; "category": string; "transmission": string; "fuelType": string; "seats": number; "dailyRateCents": number; "securityDepositCents": number; "location": string; "jurisdictionCode": string | null }>; "nextCursor": string | null } };
  "vehicle": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "slug": string; "year": number; "make": string; "model": string; "category": string; "transmission": string; "fuelType": string; "seats": number; "dailyRateCents": number; "securityDepositCents": number; "location": string; "jurisdictionCode": string | null } };
  "listingPhotos": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "items": Array<{ "id": string; "path": string; "alt": string }> } };
  "availability": { input: { params: { "id": string }; body: { "pickupAt": string; "returnAt": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "available": boolean; "authoritativeAt": string; "holdRequired": true } };
  "reservations": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "confirmationNumber": string; "vehicleId": string; "status": string; "pickupAt": string; "returnAt": string; "bookingTimezone": string; "pickupLocation": string; "expiresAt": string | null; "subtotalCents": number; "extrasCents": number; "discountCents": number; "taxCents": number; "feesCents": number; "totalCents": number; "depositCents": number; "bookingFingerprint": string | null }>; "nextCursor": string | null } };
  "reservation": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "confirmationNumber": string; "vehicleId": string; "status": string; "pickupAt": string; "returnAt": string; "bookingTimezone": string; "pickupLocation": string; "expiresAt": string | null; "subtotalCents": number; "extrasCents": number; "discountCents": number; "taxCents": number; "feesCents": number; "totalCents": number; "depositCents": number; "bookingFingerprint": string | null } };
  "hold": { input: { params?: never; body: { "draftId": string; "revision": number; "vehicleId": string; "pickupAt": string; "returnAt": string; "extraIds"?: Array<string>; "couponCode"?: string }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "checkout": { input: { params: { "id": string }; body: { "bookingFingerprint"?: string; "driver": { "firstName": string; "lastName": string; "dob": string; "email": string; "phone": string; "address": string; "city": string; "state": string; "zip": string; "country"?: string; "licenseNumber": string; "licenseState": string; "licenseExpiration": string }; "documentIds": { "front"?: string; "back"?: string; "selfie"?: string }; "agreementAccepted": true; "agreementContentHash": string }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string; "success": true } };
  "agreementPreview": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "type": "RENTAL_AGREEMENT"; "version": string; "content": string; "contentHash": string; "needsAttorneyReview": boolean } };
  "pricing": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "subtotalCents": number; "extrasCents": number; "discountCents": number; "taxCents": number; "totalCents": number; "depositCents": number; "platformFeeCents": number | null; "protectionCents": number | null; "processingCents": number | null; "hostCommissionCents"?: number | null; "hostEarningsCents"?: number | null; "reserveCents"?: number | null; "approval": "SAMPLE_UNAPPROVED" } };
  "tripCancel": { input: { params: { "id": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "tripStart": { input: { params: { "id": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "tripKeys": { input: { params: { "id": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "tripReturn": { input: { params: { "id": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "tripComplete": { input: { params: { "id": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "paymentStatus": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "status": string; "depositRequired": boolean; "outcome": string; "paidCents": number; "refundedCents": number; "pendingRefundCents": number; "refundStatus": string; "depositValid": boolean; "moneyAvailable": boolean; "financialEligible": boolean; "rentalPaymentStatus": string | null; "depositStatus": string | null } };
  "agreements": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "items": Array<{ "id": string; "type": string; "documentVersion": string; "contentHash": string; "signedAt": string }> } };
  "trip": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "trip": { "startedAt": string | null; "endedAt": string | null; "startMileage": number | null; "endMileage": number | null; "startFuelLevel": number | null; "endFuelLevel": number | null } | null; "gate": { "canStart": boolean; "reasons": Array<string> } } };
  "reservationDocuments": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "items": Array<{ "id": string; "type": string; "status": string; "malwareScanStatus": string }> } };
  "documents": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "type": string; "status": string; "malwareScanStatus": string; "reservationId": string | null }>; "nextCursor": string | null } };
  "initializeUpload": { input: { params?: never; body: { "reservationId"?: string; "type": "LICENSE_FRONT" | "LICENSE_BACK" | "SELFIE_WITH_LICENSE" | "INSPECTION"; "mimeType": "image/jpeg" | "image/png" | "image/webp"; "sha256": string; "size": number }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string; "expiresAt": string; "maxBytes": number } };
  "finalizeUpload": { input: { params: { "id": string }; body: Uint8Array; idempotencyKey: string; fileAccess?: never; query?: never; contentType: "image/png" | "image/jpeg" | "image/webp" }; output: { "id": string } };
  "documentAccess": { input: { params?: never; body: { "documentId": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "capability": string; "expiresInSeconds": 60; "documentId": string } };
  "privateDocument": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess: string; query?: never }; output: ArrayBuffer };
  "reports": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "items": Array<{ "id": string; "phase": string; "submittedByRole": string; "own": boolean; "mileage": number; "fuelLevel": number; "damageNotes": string | null; "acceptedAt": string | null; "photos": Array<{ "id": string; "category": "EXTERIOR" | "INTERIOR" | "ODOMETER" | "FUEL_GAUGE" | "DAMAGE" }> }> } };
  "reportPhoto": { input: { params: { "id": string; "reportId": string; "photoId": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: ArrayBuffer };
  "submitReport": { input: { params: { "id": string }; body: { "phase": "PRE_TRIP" | "POST_TRIP"; "mileage": number; "fuelLevel": number; "damageNotes"?: string; "photos": Array<{ "uploadId": string; "category": "EXTERIOR" | "INTERIOR" | "ODOMETER" | "FUEL_GAUGE" | "DAMAGE" }> }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "acceptReport": { input: { params: { "id": string; "reportId": string }; body: Record<string, never>; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "conversations": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "reservationId": string | null; "vehicleId": string; "updatedAt": string }>; "nextCursor": string | null } };
  "messages": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "body": string; "createdAt": string; "editedAt": string | null; "version": number }>; "nextCursor": string | null } };
  "openConversation": { input: { params?: never; body: { "reservationId": string }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "sendMessage": { input: { params: { "id": string }; body: { "body": string }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "notifications": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "category": string; "title": string; "readAt": string | null; "createdAt": string; "resourceType": string; "resourceId": string }>; "nextCursor": string | null } };
  "cases": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "kind": string; "category": string; "title": string; "state": string; "version": number; "reservationId": string | null }>; "nextCursor": string | null } };
  "serviceCase": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "kind": string; "category": string; "title": string; "state": string; "version": number; "reservationId": string | null } };
  "caseEvents": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "body": string; "action": string; "createdAt": string }>; "nextCursor": string | null } };
  "openCase": { input: { params?: never; body: { "kind": "CLAIM" | "DISPUTE" | "INCIDENT" | "TICKET"; "reservationId"?: string; "category": string; "title": string; "body": string; "linkedCaseId"?: string; "location"?: string; "severity"?: "MINOR" | "MODERATE" | "SEVERE"; "occurredAt"?: string; "people"?: string; "policeReport"?: string; "provider"?: string; "originalPhotoIds"?: Array<string> }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "replyCase": { input: { params: { "id": string }; body: { "body": string; "version": number }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "saveReview": { input: { params?: never; body: { "reservationId": string; "subject": "VEHICLE" | "HOST" | "CUSTOMER"; "rating": number; "body": string; "cleanliness": number; "communication": number; "accuracy": number; "version"?: number }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string } };
  "hostFleet": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "slug": string; "year": number; "make": string; "model": string; "category": string; "transmission": string; "fuelType": string; "seats": number; "dailyRateCents": number; "securityDepositCents": number; "location": string; "jurisdictionCode": string | null; "status": string; "listingApproval": string }>; "nextCursor": string | null } };
  "hostContext": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "role": "OWNER" | "MANAGER" | "STAFF"; "name": string; "canManageFleet": boolean; "canViewEarnings": boolean; "fleetCount": number; "upcomingCount": number; "activeCount": number; "liveFinanceEnabled": false } };
  "hostVehicle": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "year": number; "make": string; "model": string; "description": string | null; "rules": string | null; "location": string; "mileage": number; "status": string; "listingApproval": string; "isDemo": boolean; "isBookable": boolean } };
  "hostCalendar": { input: { params: { "id": string }; body: { "startAt": string; "endAt": string }; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "blocks": Array<{ "id": string; "startAt": string; "endAt": string; "reason": string; "notes": string | null }>; "reservations": Array<{ "id": string; "confirmationNumber": string; "status": string; "pickupAt": string; "returnAt": string }>; "truncated": boolean } };
  "hostAvailability": { input: { params: { "id": string }; body: { "action": "block"; "startAt": string; "endAt": string; "reason": "MAINTENANCE" | "OWNER_REQUEST" | "OTHER"; "notes": string } | { "action": "unblock"; "id": string } | { "action": "availability"; "isBookable": boolean }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "success": boolean } };
  "hostTrip": { input: { params: { "id": string }; body?: never; idempotencyKey?: never; fileAccess?: never; query?: never }; output: { "id": string; "customerName": string; "handoffVerified": boolean; "keysReleased": boolean; "keyReleaseGate": { "canStart": boolean; "reasons": Array<string> } } };
  "hostHandoff": { input: { params: { "id": string }; body: { "licenseMatchesUpload": boolean; "physicalLicenseUnexpired": boolean; "selfieMatchesCustomer": boolean; "notes"?: string }; idempotencyKey: string; fileAccess?: never; query?: never }; output: { "id": string; "verified": boolean } };
  "hostReservations": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "confirmationNumber": string; "vehicleId": string; "status": string; "pickupAt": string; "returnAt": string; "bookingTimezone": string; "pickupLocation": string; "expiresAt": string | null; "subtotalCents": number; "extrasCents": number; "discountCents": number; "taxCents": number; "feesCents": number; "totalCents": number; "depositCents": number; "bookingFingerprint": string | null }>; "nextCursor": string | null } };
  "hostEarnings": { input: { params?: never; body?: never; idempotencyKey?: never; fileAccess?: never; query?: { limit?: number; cursor?: string } }; output: { "items": Array<{ "id": string; "reservationId": string; "currency": string; "grossCents": number; "commissionCents": number; "hostDiscountCents": number; "netCents": number; "refundedCents": number; "adjustmentCents": number; "held": boolean; "payoutEnabled": false }>; "nextCursor": string | null } };
}
export const operationMetadata = {
  "requestPhoneCode": {
    "path": "/auth/request-phone-code",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "phoneSignIn": {
    "path": "/auth/phone-sign-in",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "requestIdentityCode": {
    "path": "/auth/request-identity-code",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "verifyIdentityCode": {
    "path": "/auth/verify-identity-code",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "loginMethods": {
    "path": "/auth/methods",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "requestCode": {
    "path": "/auth/request-code",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "signIn": {
    "path": "/auth/sign-in",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "refresh": {
    "path": "/auth/refresh",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "logout": {
    "path": "/auth/logout",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "logoutAll": {
    "path": "/auth/logout-all",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "revokeDevice": {
    "path": "/auth/revoke",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "devices": {
    "path": "/auth/devices",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "me": {
    "path": "/me",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "vehicles": {
    "path": "/vehicles",
    "method": "GET",
    "auth": false,
    "binary": null
  },
  "vehicle": {
    "path": "/vehicles/{id}",
    "method": "GET",
    "auth": false,
    "binary": null
  },
  "listingPhotos": {
    "path": "/vehicles/{id}/photos",
    "method": "GET",
    "auth": false,
    "binary": null
  },
  "availability": {
    "path": "/vehicles/{id}/availability",
    "method": "POST",
    "auth": false,
    "binary": null
  },
  "reservations": {
    "path": "/reservations",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "reservation": {
    "path": "/reservations/{id}",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hold": {
    "path": "/reservations/hold",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "checkout": {
    "path": "/reservations/{id}/checkout",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "agreementPreview": {
    "path": "/reservations/{id}/agreement-preview",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "pricing": {
    "path": "/reservations/{id}/pricing",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "tripCancel": {
    "path": "/reservations/{id}/cancel",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "tripStart": {
    "path": "/reservations/{id}/start",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "tripKeys": {
    "path": "/reservations/{id}/keys",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "tripReturn": {
    "path": "/reservations/{id}/return",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "tripComplete": {
    "path": "/reservations/{id}/complete",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "paymentStatus": {
    "path": "/reservations/{id}/payment-status",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "agreements": {
    "path": "/reservations/{id}/agreements",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "trip": {
    "path": "/reservations/{id}/trip",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "reservationDocuments": {
    "path": "/reservations/{id}/documents",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "documents": {
    "path": "/documents",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "initializeUpload": {
    "path": "/uploads",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "finalizeUpload": {
    "path": "/uploads/{id}/finalize",
    "method": "POST",
    "auth": true,
    "binary": "request"
  },
  "documentAccess": {
    "path": "/files/access",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "privateDocument": {
    "path": "/files/{id}",
    "method": "GET",
    "auth": true,
    "binary": "response"
  },
  "reports": {
    "path": "/reservations/{id}/reports",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "reportPhoto": {
    "path": "/reservations/{id}/reports/{reportId}/photos/{photoId}",
    "method": "GET",
    "auth": true,
    "binary": "response"
  },
  "submitReport": {
    "path": "/reservations/{id}/reports",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "acceptReport": {
    "path": "/reservations/{id}/reports/{reportId}/accept",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "conversations": {
    "path": "/conversations",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "messages": {
    "path": "/conversations/{id}",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "openConversation": {
    "path": "/conversations",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "sendMessage": {
    "path": "/conversations/{id}/messages",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "notifications": {
    "path": "/notifications",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "cases": {
    "path": "/cases",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "serviceCase": {
    "path": "/cases/{id}",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "caseEvents": {
    "path": "/cases/{id}/events",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "openCase": {
    "path": "/cases",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "replyCase": {
    "path": "/cases/{id}/reply",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "saveReview": {
    "path": "/reviews",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "hostFleet": {
    "path": "/host/fleet",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hostContext": {
    "path": "/host/context",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hostVehicle": {
    "path": "/host/vehicles/{id}",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hostCalendar": {
    "path": "/host/vehicles/{id}/calendar",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "hostAvailability": {
    "path": "/host/vehicles/{id}/availability",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "hostTrip": {
    "path": "/host/trips/{id}",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hostHandoff": {
    "path": "/host/trips/{id}/handoff",
    "method": "POST",
    "auth": true,
    "binary": null
  },
  "hostReservations": {
    "path": "/host/reservations",
    "method": "GET",
    "auth": true,
    "binary": null
  },
  "hostEarnings": {
    "path": "/host/earnings",
    "method": "GET",
    "auth": true,
    "binary": null
  }
} as const;
