import { FinanceAccounts } from "@/components/marketplace/finance-accounts";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { adminFinancePage } from "@/lib/finance-page-access";
import { money } from "@/lib/finance-access";
import { FinanceWorkspace,FinanceRestricted,FinanceEmpty,FinanceStatus } from "@/components/marketplace/finance-workspace";
import { Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
export default async function FinanceAdminPage(){const actor=await adminFinancePage();if(!actor)return <FinanceRestricted/>;
 const [payments,refunds,deposits,batches,issues,backlog,adjustments,totals]=await Promise.all([prisma.payment.findMany({orderBy:{createdAt:"desc"},take:20,select:{id:true,type:true,status:true,amountCents:true,currency:true}}),prisma.refund.findMany({orderBy:{createdAt:"desc"},take:20,select:{id:true,status:true,amountCents:true}}),prisma.securityDeposit.findMany({take:20,orderBy:{createdAt:"desc"},select:{id:true,status:true,amountCents:true,currency:true}}),prisma.payoutBatch.findMany({orderBy:{createdAt:"desc"},take:25}),prisma.financeIssue.count({where:{status:{not:"RESOLVED"}}}),prisma.financialOperation.count({where:{kind:{startsWith:"FINANCE_"},state:{in:["READY","RETRY","RUNNING","POLL","REVIEW"]}}}),prisma.financeAdjustment.findMany({where:{state:"PROPOSED"},take:20,orderBy:{createdAt:"asc"}}),prisma.$queryRaw<Array<{account:string;currency:string;balance:string}>>`SELECT l.account,j.currency,sum(l."creditCents"::bigint-l."debitCents"::bigint)::text balance FROM "LedgerLine" l JOIN "LedgerJournal" j ON j.id=l."journalId" GROUP BY l.account,j.currency ORDER BY j.currency,l.account`]);
 return <FinanceWorkspace admin title="Financial administration" description="Provider movement, accounting and reconciliation stay separate. Unexplained differences remain visible until supported by evidence."><div className="grid gap-4 sm:grid-cols-3">{[["Reconciliation cases",issues],["Worker backlog",backlog],["Pending adjustments",adjustments.length]].map(([label,value])=><Panel key={label} title={String(label)}><p className="text-4xl text-gold-bright">{value}</p></Panel>)}</div>
  <FinanceAccounts userId={actor.id}/>
  <Panel title="Payout batches">{batches.length?batches.map(b=><Link key={b.id} href={`/finance/payouts/${b.id}`} className="flex flex-wrap justify-between gap-3 border-b border-white/10 py-4 text-white"><span>{money(b.amountCents,b.currency)} · {b.createdAt.toLocaleDateString()}</span><FinanceStatus value={b.state}/></Link>):<FinanceEmpty>No payout batches.</FinanceEmpty>}</Panel>
  <div className="grid gap-6 lg:grid-cols-3">{[["Payments",payments],["Refunds",refunds],["Deposits",deposits]].map(([label,values])=><Panel key={String(label)} title={String(label)}>{(values as typeof payments).length?(values as typeof payments).map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 border-b border-white/10 py-3 text-sm"><span className="text-white">{money(p.amountCents,p.currency??"usd")}</span><FinanceStatus value={p.status}/></div>):<FinanceEmpty>No records.</FinanceEmpty>}</Panel>)}</div>
  <Panel title="Ledger balances by currency"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{totals.map(t=><div key={t.currency+t.account} className="min-w-0 rounded-xl border border-white/10 p-4"><p className="break-words text-xs text-silver">{t.account.replaceAll("_"," ")}</p><p className="mt-2 text-xl text-white">{money(Number(t.balance),t.currency)}</p><p className="text-xs text-silver">Credit less debit</p></div>)}</div><a href="/api/finance/export" className="mt-6 inline-block text-gold-bright">Download latest 1,000 journals as safe CSV ↓</a></Panel>
  <Panel title="Propose a financial adjustment"><ActionForm endpoint="/api/finance" action="adjustment" fields={[{name:"reservationId",label:"Reservation ID"},{name:"evidenceId",label:"Resolved financial case ID"},{name:"kind",label:"Allocation",options:["HOST_CREDIT","HOST_DEBIT","CLAIM_ADJUSTMENT","ADDITIONAL_CHARGE_ALLOCATION"]},{name:"amountCents",label:"Amount (USD)",type:"money",min:0.01},{name:"reason",label:"Evidence and reason",type:"textarea"}]} label="Submit for independent approval"/></Panel>
  {actor.role==="SUPER_ADMIN"&&<Panel title="Independent adjustment approval"><ActionForm endpoint="/api/finance" action="stepUp" label="Send finance verification code"/>{adjustments.map(a=><div key={a.id} className="mt-5 rounded-xl border border-white/10 p-4"><p className="mb-4 text-silver">{a.kind.replaceAll("_"," ")} · {money(a.amountCents)} · {a.reason}</p><ActionForm endpoint="/api/finance" action="approveAdjustment" values={{id:a.id}} fields={[{name:"stepUpCode",label:"Fresh finance verification code"}]} label="Approve with evidence"/></div>)}</Panel>}
  <Panel title="Platform reports"><ActionForm endpoint="/api/finance" action="document" values={{newVersion:true}} fields={[{name:"kind",label:"Report",options:["COMMISSION_REPORT","TAX_REPORT","LIABILITY_REPORT","RECONCILIATION_REPORT"]}]} label="Issue report PDF" redirectTo="/api/finance/documents/:id"/></Panel>
 </FinanceWorkspace>;
}
