import { certifyAccounting } from "@/lib/finance-completeness";
import { transferMayHaveMoved } from "@/lib/payout-movement";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { financeAdmin,financeHost,financeStepUp } from "@/lib/finance-access";
import { independentCaseActor } from "@/lib/case-decision-authority";
import { lockReservation } from "@/lib/financial-locks";
import { journal,accountReservation,financeIssue } from "@/lib/finance-ledger";
import { payoutSchema,selectedRule,lossSchema,roundBps } from "@/lib/finance-rules";
import { MarketplaceError } from "@/lib/marketplace";
import { nextPayoutCutoff } from "@/lib/payout-workers";
import { lockFinanceOperation } from "@/lib/payout-authority";
import { retrieveFinanceProviderObject,discoverFinanceProviderObject,financeStripe } from "@/lib/finance-provider";
import { applyFinanceObject } from "@/lib/payout-operations";

async function independentFinance(tx:Parameters<typeof financeAdmin>[0],userId:string,reservationId:string){const r=await tx.reservation.findUniqueOrThrow({where:{id:reservationId}});await independentCaseActor(tx,{id:"financial:"+r.id,kind:"CLAIM",reservationId:r.id,vehicleId:r.vehicleId,openedById:r.customerId},userId);}
export async function proposeAdjustment(userId:string,input:unknown){
 const d=z.object({reservationId:z.string(),kind:z.enum(["HOST_CREDIT","HOST_DEBIT","CLAIM_ADJUSTMENT","ADDITIONAL_CHARGE_ALLOCATION"]),amountCents:z.coerce.number().int().positive().max(100000000),reason:z.string().min(10).max(1000),evidenceId:z.string().min(1)}).parse(input);
 return prisma.$transaction(async tx=>{await lockReservation(tx,d.reservationId);await financeAdmin(tx,userId);await accountReservation(tx,d.reservationId);const e=await tx.hostEarning.findUniqueOrThrow({where:{reservationId:d.reservationId}});if(d.amountCents>e.grossCents)throw new MarketplaceError("Adjustment exceeds reservation gross evidence.");const evidence=await tx.financialCase.findFirst({where:{id:d.evidenceId,reservationId:d.reservationId,status:"RESOLVED"}});if(!evidence)throw new MarketplaceError("A resolved financial settlement case is required; operational cases cannot authorize money.");const row=await tx.financeAdjustment.create({data:{...d,createdById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.adjustment.proposed",entityType:"FinanceAdjustment",entityId:row.id,metadata:{reason:d.reason}}});return{id:row.id};});
}
export async function approveAdjustment(userId:string,id:string,code:string){return prisma.$transaction(async tx=>{
 const prior=await tx.financeAdjustment.findUniqueOrThrow({where:{id}});await lockReservation(tx,prior.reservationId);await tx.$queryRaw`SELECT id FROM "FinanceAdjustment" WHERE id=${id} FOR UPDATE`;const a=await tx.financeAdjustment.findUniqueOrThrow({where:{id}});await independentFinance(tx,userId,a.reservationId);if(a.createdById===userId)throw new MarketplaceError("An independent second finance administrator must approve.",403);if(a.state!=="PROPOSED")throw new MarketplaceError("Adjustment already decided.",409);
 const evidence=await tx.financialCase.findFirst({where:{id:a.evidenceId,reservationId:a.reservationId,status:"RESOLVED"}});if(!evidence||evidence.amountCents===null||evidence.currency!=="usd")throw new MarketplaceError("Amount-specific settlement authority is required.",409);
 const used=await tx.financeAdjustment.aggregate({where:{evidenceId:a.evidenceId,state:"APPROVED"},_sum:{amountCents:true}});if((used._sum.amountCents??0)+a.amountCents>evidence.amountCents)throw new MarketplaceError("Adjustment exceeds the remaining approved settlement amount.",409);
 await accountReservation(tx,a.reservationId);const e=await tx.hostEarning.findUniqueOrThrow({where:{reservationId:a.reservationId}});if(await tx.payoutItem.count({where:{earningId:e.id,active:true}}))throw new MarketplaceError("Resolve the in-flight/paid batch through recovery before changing earnings.",409);
 const credit=["HOST_CREDIT","ADDITIONAL_CHARGE_ALLOCATION"].includes(a.kind);if(!credit&&e.netCents-e.refundedCents+e.adjustmentCents<a.amountCents)throw new MarketplaceError("Adjustment exceeds available host balance.",409);
 if(a.kind==="ADDITIONAL_CHARGE_ALLOCATION"){const collected=await tx.payment.aggregate({where:{reservationId:a.reservationId,type:"ADDITIONAL_CHARGE",status:"SUCCEEDED",currency:e.currency},_sum:{amountCents:true}}),allocated=await tx.financeAdjustment.aggregate({where:{reservationId:a.reservationId,kind:a.kind,state:"APPROVED"},_sum:{amountCents:true}});if((collected._sum.amountCents??0)-(allocated._sum.amountCents??0)<a.amountCents)throw new MarketplaceError("Provider-confirmed unallocated additional charge evidence required.",409);}
 await financeStepUp(tx,userId,code);
 const posted=await journal(tx,{key:"adjustment:"+a.id,kind:a.kind,currency:e.currency,reservationId:a.reservationId,hostId:e.hostId,description:a.reason,lines:credit?[{account:a.kind==="ADDITIONAL_CHARGE_ALLOCATION"?"ADDITIONAL_CHARGE_LIABILITY":"PLATFORM_ADJUSTMENT_EXPENSE",debitCents:a.amountCents},{account:"HOST_PAYABLE",creditCents:a.amountCents}]:[{account:"HOST_PAYABLE",debitCents:a.amountCents},{account:"PLATFORM_ADJUSTMENT_RECOVERY",creditCents:a.amountCents}]});
 await tx.hostEarning.update({where:{id:e.id},data:{adjustmentCents:{increment:credit?a.amountCents:-a.amountCents}}});await tx.financeAdjustment.update({where:{id},data:{state:"APPROVED",approvedById:userId,journalId:posted.id}});await tx.auditLog.create({data:{actorId:userId,action:"finance.adjustment.approved",entityType:"FinanceAdjustment",entityId:id,metadata:{reason:a.reason,journalId:posted.id}}});await certifyAccounting(tx,a.reservationId);return{id};
});}
export async function updatePayoutSchedule(userId:string,input:unknown){const d=z.object({schedule:z.enum(["MANUAL","WEEKLY","TWICE_MONTHLY","MONTHLY"]),timezone:z.string(),minimumCents:z.coerce.number().int().min(1).max(100000000)}).parse(input);return prisma.$transaction(async tx=>{const {host}=await financeHost(tx,userId,undefined,true);await tx.$queryRaw`SELECT financial_guard_xact(${"host-finance:"+host.id})`;const rule=await selectedRule(tx,"PAYOUT",[{scope:"HOST",scopeId:host.id},{scope:"DEFAULT",scopeId:"*"}]);if(!rule)throw new MarketplaceError("Business-approved payout policy required.",409);const p=payoutSchema.parse(rule.config);if(!p.hostMaySelect||!p.allowedSchedules.includes(d.schedule)||d.minimumCents<p.minimumCents)throw new MarketplaceError("Schedule or threshold is not approved.",403);try{new Intl.DateTimeFormat("en",{timeZone:d.timezone});}catch{throw new MarketplaceError("Choose an IANA time zone.");}await tx.connectAccount.update({where:{hostId:host.id},data:{...d,nextRunAt:nextPayoutCutoff(d.schedule,d.timezone)}});await tx.auditLog.create({data:{actorId:userId,action:"finance.schedule.changed",entityType:"HostProfile",entityId:host.id,metadata:d}});return{success:true};});}
export async function grantFinance(userId:string,employeeId:string,manage:boolean){return prisma.$transaction(async tx=>{const {host,owner}=await financeHost(tx,userId,undefined,true);if(!owner)throw new MarketplaceError("Only the host owner grants finance access.",403);const e=await tx.hostEmployee.findFirst({where:{id:employeeId,hostId:host.id,isActive:true}});if(!e||manage&&e.role!=="MANAGER")throw new MarketplaceError("Choose a current employee or finance manager.");await tx.financeGrant.upsert({where:{hostId_userId:{hostId:host.id,userId:e.userId}},create:{hostId:host.id,userId:e.userId,manage,grantedById:userId},update:{manage,grantedById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.permission.granted",entityType:"HostEmployee",entityId:employeeId,metadata:{manage}}});return{success:true};});}
export async function resolveFinanceIssue(userId:string,id:string,code:string,reason:string){
 await financeAdmin(prisma,userId,true);if(reason.trim().length<10)throw new MarketplaceError("A specific reconciliation reason is required.");
 const issue=await prisma.financeIssue.findUniqueOrThrow({where:{id}});if(!issue.operationId||issue.kind!=="PROVIDER_UNCERTAIN")throw new MarketplaceError("This difference needs accounting evidence; it cannot be written off by closing a queue item.",409);
 const op=await prisma.financialOperation.findUniqueOrThrow({where:{id:issue.operationId}});
 if(!op.providerId&&!await prisma.financialDispatch.count({where:{operationId:op.id,phase:{in:["DISPATCHED","SUCCEEDED","UNCERTAIN"]}}}))return prisma.$transaction(async tx=>{
  await lockFinanceOperation(tx,op);const current=await tx.financialOperation.findUniqueOrThrow({where:{id:op.id}});
  if(current.providerId||current.state!=="REVIEW"||current.leaseExpiresAt&&current.leaseExpiresAt>new Date()||await tx.financialDispatch.count({where:{operationId:op.id,phase:{in:["DISPATCHED","SUCCEEDED","UNCERTAIN"]}}}))throw new MarketplaceError("Provider dispatch evidence changed; reconcile the existing outcome.",409);
  const batchId=(current.payload as {batchId?:string}).batchId;if(batchId)for(const item of await tx.payoutItem.findMany({where:{batchId}}))await independentFinance(tx,userId,item.reservationId);
  await financeStepUp(tx,userId,code);await tx.financialOperation.update({where:{id:op.id},data:{state:"READY",consecutiveFailures:0,leaseToken:null,leaseExpiresAt:null,nextAttemptAt:new Date(),lastError:null}});
  await tx.financeIssue.update({where:{id},data:{status:"RESOLVED",resolvedById:userId,resolution:"Verified never dispatched; resume original immutable intent: "+reason}});
  await tx.auditLog.create({data:{actorId:userId,action:"finance.undispatched.resumed",entityType:"FinancialOperation",entityId:op.id,metadata:{reason}}});return{id};
 });
 const result=op.providerId?await retrieveFinanceProviderObject(op,op.providerId):await discoverFinanceProviderObject(op);
 if(!result)throw new MarketplaceError("Provider outcome remains unknown. No replay or write-off is authorized.",409);
 return prisma.$transaction(async tx=>{await lockFinanceOperation(tx,op);const current=await tx.financialOperation.findUniqueOrThrow({where:{id:op.id}});if(current.leaseExpiresAt&&current.leaseExpiresAt>new Date())throw new MarketplaceError("An active recovery worker still owns this operation.",409);const currentIssue=await tx.financeIssue.findUniqueOrThrow({where:{id}});if(currentIssue.status==="RESOLVED")return{id};const batchId=(op.payload as {batchId?:string}).batchId;if(batchId){for(const item of await tx.payoutItem.findMany({where:{batchId}}))await independentFinance(tx,userId,item.reservationId);}await financeStepUp(tx,userId,code);await applyFinanceObject(tx,op,result);await tx.financialOperation.update({where:{id:op.id},data:{providerId:result.id,result:JSON.parse(JSON.stringify(result)),state:"OBSERVED",leaseToken:null,leaseExpiresAt:null,lastError:null}});await tx.financeIssue.update({where:{id},data:{status:"RESOLVED",resolution:reason,resolvedById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.reconciliation.resolved",entityType:"FinanceIssue",entityId:id,metadata:{reason,providerId:result.id}}});return{id};});
}

export async function allocateChargeback(userId:string,issueId:string,code:string){return prisma.$transaction(async tx=>{
 await financeAdmin(tx,userId,true);const issue=await tx.financeIssue.findUniqueOrThrow({where:{id:issueId}});if(issue.kind!=="CHARGEBACK_ALLOCATION"||!issue.reservationId)throw new MarketplaceError("A retained chargeback allocation case is required.",409);
 await lockReservation(tx,issue.reservationId);await independentFinance(tx,userId,issue.reservationId);const evidence=issue.evidence as {providerId:string};const d=await tx.providerDispute.findUniqueOrThrow({where:{id:evidence.providerId}});const authoritative=await financeStripe().disputes.retrieve(d.id);if(authoritative.status!=="lost"||authoritative.amount!==d.amountCents||authoritative.currency!==d.currency)throw new MarketplaceError("Current Stripe evidence does not authorize this loss allocation.",409);
 if(await tx.ledgerJournal.findUnique({where:{key:"chargeback-allocation:"+d.id}}))return{id:issueId};
 const s=await tx.financeSnapshot.findUniqueOrThrow({where:{reservationId:issue.reservationId}}),policy=lossSchema.safeParse((s.settlement as {loss?:unknown}).loss);if(!s.approved||!policy.success)throw new MarketplaceError("Frozen business-approved chargeback policy required.",409);
 await accountReservation(tx,issue.reservationId);const earning=await tx.hostEarning.findUniqueOrThrow({where:{reservationId:issue.reservationId}});await tx.$queryRaw`SELECT financial_guard_xact(${"host-finance:"+earning.hostId})`;
 const hostCents=Math.min(Math.max(0,earning.netCents-earning.refundedCents+earning.adjustmentCents),roundBps(d.amountCents,policy.data.chargebackHostBps));const item=await tx.payoutItem.findFirst({where:{earningId:earning.id,active:true}}),batch=item?await tx.payoutBatch.findUniqueOrThrow({where:{id:item.batchId}}):null;
 const sent=batch?await transferMayHaveMoved(tx,batch.id):false;
 await financeStepUp(tx,userId,code);const allocation=await journal(tx,{key:"chargeback-allocation:"+d.id,kind:"CHARGEBACK_ALLOCATION",currency:d.currency,reservationId:issue.reservationId,hostId:earning.hostId,providerId:d.id,description:"Independent approval of frozen chargeback loss allocation",lines:[{account:sent?"HOST_RECEIVABLE":"HOST_PAYABLE",debitCents:hostCents},{account:"PLATFORM_CHARGEBACK_EXPENSE",debitCents:d.amountCents-hostCents},{account:"CHARGEBACK_SUSPENSE",creditCents:d.amountCents}]});
 if(hostCents)await tx.hostEarning.update({where:{id:earning.id},data:{adjustmentCents:{decrement:hostCents}}});
 if(batch&&hostCents)await financeIssue(tx,{key:"refund-recovery:dispute:"+d.id,kind:sent?"POST_PAYOUT_LOSS":"BATCH_CHANGED",hostId:earning.hostId,reservationId:issue.reservationId,reason:"Recover the independently approved host share of the chargeback",evidence:{batchId:batch.id,refundId:"dispute:"+d.id,hostCents,reverseTransfers:policy.data.reverseTransfers}});
 await tx.financeIssue.update({where:{id:issueId},data:{status:"RESOLVED",resolvedById:userId,resolution:"Frozen policy allocated in journal "+allocation.id}});await tx.auditLog.create({data:{actorId:userId,action:"finance.chargeback.allocated",entityType:"ProviderDispute",entityId:d.id,metadata:{journalId:allocation.id,hostCents}}});await certifyAccounting(tx,issue.reservationId);return{id:issueId};
},{timeout:20000});}

export async function deactivateConnect(userId:string,hostId:string,code:string,reason:string){
 if(reason.trim().length<10)throw new MarketplaceError("A specific suspension reason is required.");
 return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT financial_guard_xact(${"host-finance:"+hostId})`;await financeStepUp(tx,userId,code);await tx.connectAccount.update({where:{hostId},data:{active:false,verificationStatus:"DEACTIVATED"}});await tx.auditLog.create({data:{actorId:userId,action:"finance.connect.deactivated",entityType:"HostProfile",entityId:hostId,metadata:{reason}}});return{success:true};});
}
export async function approveTaxExemption(userId:string,input:unknown){
 const d=z.object({customerId:z.string().min(1),jurisdiction:z.string().trim().min(2).max(120),evidenceReference:z.string().regex(/^[A-Za-z0-9:_-]{6,160}$/),expiresAt:z.string().datetime(),reason:z.string().trim().min(10).max(1000),stepUpCode:z.string(),reviewAttestation:z.literal("yes")}).parse(input);
 if(new Date(d.expiresAt)<=new Date())throw new MarketplaceError("Exemption evidence must remain valid.");
 return prisma.$transaction(async tx=>{await financeStepUp(tx,userId,d.stepUpCode);await tx.user.findUniqueOrThrow({where:{id:d.customerId}});const row=await tx.taxExemption.create({data:{customerId:d.customerId,jurisdiction:d.jurisdiction,evidenceReference:d.evidenceReference,expiresAt:new Date(d.expiresAt),approvedById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.tax_exemption.approved",entityType:"TaxExemption",entityId:row.id,metadata:{reason:d.reason,evidenceReference:d.evidenceReference,jurisdiction:d.jurisdiction}}});return{id:row.id};});
}

export async function retryScheduledFinance(userId:string,id:string,code:string,reason:string){
 if(reason.trim().length<10)throw new MarketplaceError("Describe the corrected delivery failure.");
 return prisma.$transaction(async tx=>{
  await financeAdmin(tx,userId,true);await tx.$queryRaw`SELECT id FROM "OutboxMessage" WHERE id=${id} FOR UPDATE`;
  const message=await tx.outboxMessage.findUniqueOrThrow({where:{id}});
  if(message.type!=="finance_schedule"||message.status!=="FAILED"||message.leaseExpiresAt&&message.leaseExpiresAt>new Date())throw new MarketplaceError("Only failed, unleased finance scheduling work may be resumed.",409);
  await financeStepUp(tx,userId,code);
  await tx.outboxMessage.update({where:{id},data:{status:"PENDING",attempts:0,nextRetryAt:new Date(),leaseToken:null,leaseExpiresAt:null,lastError:null}});
  await tx.auditLog.create({data:{actorId:userId,action:"finance.schedule.delivery_resumed",entityType:"OutboxMessage",entityId:id,metadata:{reason}}});return{id};
 });
}
