import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { financeAdmin,financeHost,financeStepUp } from "@/lib/finance-access";
import { independentCaseActor } from "@/lib/case-decision-authority";
import { lockReservation } from "@/lib/financial-locks";
import { journal,accountReservation } from "@/lib/finance-ledger";
import { payoutSchema,selectedRule } from "@/lib/finance-rules";
import { MarketplaceError } from "@/lib/marketplace";
import { nextPayoutCutoff } from "@/lib/payout-workers";
import { lockFinanceOperation } from "@/lib/payout-authority";
import { retrieveFinanceProviderObject,discoverFinanceProviderObject } from "@/lib/finance-provider";
import { applyFinanceObject } from "@/lib/payout-operations";

async function independentFinance(tx:Parameters<typeof financeAdmin>[0],userId:string,reservationId:string){const r=await tx.reservation.findUniqueOrThrow({where:{id:reservationId}});await independentCaseActor(tx,{id:"financial:"+r.id,kind:"CLAIM",reservationId:r.id,vehicleId:r.vehicleId,openedById:r.customerId},userId);}
export async function proposeAdjustment(userId:string,input:unknown){
 const d=z.object({reservationId:z.string(),kind:z.enum(["HOST_CREDIT","HOST_DEBIT","CLAIM_ADJUSTMENT","ADDITIONAL_CHARGE_ALLOCATION"]),amountCents:z.coerce.number().int().positive().max(100000000),reason:z.string().min(10).max(1000),evidenceId:z.string().min(1)}).parse(input);
 return prisma.$transaction(async tx=>{await lockReservation(tx,d.reservationId);await financeAdmin(tx,userId);await accountReservation(tx,d.reservationId);const e=await tx.hostEarning.findUniqueOrThrow({where:{reservationId:d.reservationId}});if(d.amountCents>e.grossCents)throw new MarketplaceError("Adjustment exceeds reservation gross evidence.");const evidence=await tx.financialCase.findFirst({where:{id:d.evidenceId,reservationId:d.reservationId,status:"RESOLVED"}});if(!evidence)throw new MarketplaceError("A resolved financial settlement case is required; operational cases cannot authorize money.");const row=await tx.financeAdjustment.create({data:{...d,createdById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.adjustment.proposed",entityType:"FinanceAdjustment",entityId:row.id,metadata:{reason:d.reason}}});return{id:row.id};});
}
export async function approveAdjustment(userId:string,id:string,code:string){return prisma.$transaction(async tx=>{
 const prior=await tx.financeAdjustment.findUniqueOrThrow({where:{id}});await lockReservation(tx,prior.reservationId);await tx.$queryRaw`SELECT id FROM "FinanceAdjustment" WHERE id=${id} FOR UPDATE`;const a=await tx.financeAdjustment.findUniqueOrThrow({where:{id}});await independentFinance(tx,userId,a.reservationId);if(a.createdById===userId)throw new MarketplaceError("An independent second finance administrator must approve.",403);if(a.state!=="PROPOSED")throw new MarketplaceError("Adjustment already decided.",409);
 const evidence=await tx.financialCase.findFirst({where:{id:a.evidenceId,reservationId:a.reservationId,status:"RESOLVED"}});if(!evidence)throw new MarketplaceError("Settlement authority changed.",409);
 const e=await tx.hostEarning.findUniqueOrThrow({where:{reservationId:a.reservationId}});if(await tx.payoutItem.count({where:{earningId:e.id,active:true}}))throw new MarketplaceError("Resolve the in-flight/paid batch through recovery before changing earnings.",409);
 const credit=["HOST_CREDIT","ADDITIONAL_CHARGE_ALLOCATION"].includes(a.kind);if(!credit&&e.netCents-e.refundedCents+e.adjustmentCents<a.amountCents)throw new MarketplaceError("Adjustment exceeds available host balance.",409);
 if(a.kind==="ADDITIONAL_CHARGE_ALLOCATION"&&!await tx.payment.count({where:{reservationId:a.reservationId,type:"ADDITIONAL_CHARGE",status:"SUCCEEDED",amountCents:{gte:a.amountCents}}}))throw new MarketplaceError("Provider-confirmed additional charge evidence required.",409);
 await financeStepUp(tx,userId,code);
 const posted=await journal(tx,{key:"adjustment:"+a.id,kind:a.kind,currency:e.currency,reservationId:a.reservationId,hostId:e.hostId,description:a.reason,lines:credit?[{account:"PLATFORM_ADJUSTMENT_EXPENSE",debitCents:a.amountCents},{account:"HOST_PAYABLE",creditCents:a.amountCents}]:[{account:"HOST_PAYABLE",debitCents:a.amountCents},{account:"PLATFORM_ADJUSTMENT_RECOVERY",creditCents:a.amountCents}]});
 await tx.hostEarning.update({where:{id:e.id},data:{adjustmentCents:{increment:credit?a.amountCents:-a.amountCents}}});await tx.financeAdjustment.update({where:{id},data:{state:"APPROVED",approvedById:userId,journalId:posted.id}});await tx.auditLog.create({data:{actorId:userId,action:"finance.adjustment.approved",entityType:"FinanceAdjustment",entityId:id,metadata:{reason:a.reason,journalId:posted.id}}});return{id};
});}
export async function updatePayoutSchedule(userId:string,input:unknown){const d=z.object({schedule:z.enum(["MANUAL","WEEKLY","TWICE_MONTHLY","MONTHLY"]),timezone:z.string(),minimumCents:z.coerce.number().int().min(1).max(100000000)}).parse(input);return prisma.$transaction(async tx=>{const {host}=await financeHost(tx,userId,undefined,true);await tx.$queryRaw`SELECT financial_guard_xact(${"host-finance:"+host.id})`;const rule=await selectedRule(tx,"PAYOUT",[{scope:"HOST",scopeId:host.id},{scope:"DEFAULT",scopeId:"*"}]);if(!rule)throw new MarketplaceError("Business-approved payout policy required.",409);const p=payoutSchema.parse(rule.config);if(!p.hostMaySelect||!p.allowedSchedules.includes(d.schedule)||d.minimumCents<p.minimumCents)throw new MarketplaceError("Schedule or threshold is not approved.",403);try{new Intl.DateTimeFormat("en",{timeZone:d.timezone});}catch{throw new MarketplaceError("Choose an IANA time zone.");}await tx.connectAccount.update({where:{hostId:host.id},data:{...d,nextRunAt:nextPayoutCutoff(d.schedule,d.timezone)}});await tx.auditLog.create({data:{actorId:userId,action:"finance.schedule.changed",entityType:"HostProfile",entityId:host.id,metadata:d}});return{success:true};});}
export async function grantFinance(userId:string,employeeId:string,manage:boolean){return prisma.$transaction(async tx=>{const {host,owner}=await financeHost(tx,userId,undefined,true);if(!owner)throw new MarketplaceError("Only the host owner grants finance access.",403);const e=await tx.hostEmployee.findFirst({where:{id:employeeId,hostId:host.id,isActive:true}});if(!e||manage&&e.role!=="MANAGER")throw new MarketplaceError("Choose a current employee or finance manager.");await tx.financeGrant.upsert({where:{hostId_userId:{hostId:host.id,userId:e.userId}},create:{hostId:host.id,userId:e.userId,manage,grantedById:userId},update:{manage,grantedById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.permission.granted",entityType:"HostEmployee",entityId:employeeId,metadata:{manage}}});return{success:true};});}
export async function resolveFinanceIssue(userId:string,id:string,code:string,reason:string){
 await financeAdmin(prisma,userId,true);if(reason.trim().length<10)throw new MarketplaceError("A specific reconciliation reason is required.");
 const issue=await prisma.financeIssue.findUniqueOrThrow({where:{id}});if(!issue.operationId)throw new MarketplaceError("This difference needs accounting evidence; it cannot be written off by closing a queue item.",409);
 const op=await prisma.financialOperation.findUniqueOrThrow({where:{id:issue.operationId}}),result=op.providerId?await retrieveFinanceProviderObject(op,op.providerId):await discoverFinanceProviderObject(op);
 if(!result)throw new MarketplaceError("Provider outcome remains unknown. No replay or write-off is authorized.",409);
 return prisma.$transaction(async tx=>{await lockFinanceOperation(tx,op);await financeStepUp(tx,userId,code);await applyFinanceObject(tx,op,result);await tx.financialOperation.update({where:{id:op.id},data:{providerId:result.id,result:JSON.parse(JSON.stringify(result)),state:"OBSERVED",leaseToken:null,leaseExpiresAt:null,lastError:null}});await tx.financeIssue.update({where:{id},data:{status:"RESOLVED",resolution:reason,resolvedById:userId}});await tx.auditLog.create({data:{actorId:userId,action:"finance.reconciliation.resolved",entityType:"FinanceIssue",entityId:id,metadata:{reason,providerId:result.id}}});return{id};});
}
