import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { marketplaceHost } from "@/lib/marketplace";
import { notFound } from "next/navigation";
import { Workspace, Panel, HostNav } from "@/components/marketplace/workspace";
import { ListingForm } from "@/components/marketplace/listing-form";
import { ActionForm } from "@/components/marketplace/action-form";
import { AvailabilityCalendar } from "@/components/marketplace/availability-calendar";
import { getSiteSettings } from "@/lib/settings";
import { DURABLE_BLOCKING_STATUSES, TRANSIENT_HOLD_STATUSES } from "@/lib/reservation-state-machine";
export default async function VehiclePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ month?: string }> }) {
  const { id } = await params, session = await auth(), { host, role } = await marketplaceHost(prisma, session!.user.id);
  const vehicle = await prisma.vehicle.findFirst({ where: { id, hostId: host.id }, include: { features: { include: { feature: true } }, blocks: { orderBy: { startAt: "asc" } }, availability: true, maintenanceRecords: { orderBy: { serviceDate: "desc" }, take: 20 }, agreementAcceptances: { where: { type: "HOST_AGREEMENT" } } } });
  if (!vehicle) notFound();
  const [owners, files, legal] = await Promise.all([prisma.vehicleOwner.findMany({ where: { hostId: host.id }, select: { id: true, name: true } }), prisma.marketplaceFile.findMany({ where: { vehicleId: id, hostId: host.id } }), prisma.legalDocument.findUnique({ where: { type: "HOST_AGREEMENT" } })]);
  const manage = role !== "STAFF";
  const zone = (await getSiteSettings()).bookingTimezone, month = (await searchParams).month ?? new Date().toISOString().slice(0, 7);
  const reservations = await prisma.reservation.findMany({ where: { vehicleId: id, OR: [{ status: { in: DURABLE_BLOCKING_STATUSES } }, { status: { in: TRANSIENT_HOLD_STATUSES }, expiresAt: { gt: new Date() } }] }, select: { pickupAt: true, returnAt: true, confirmationNumber: true } });
  return <Workspace eyebrow="Your fleet" title={`${vehicle.year} ${vehicle.make} ${vehicle.model}`} description={`Listing: ${vehicle.listingApproval}. Availability: ${vehicle.availability?.isBookable ? "accepting bookings" : "paused"}.`}><HostNav />
    <Panel title="Vehicle and pricing">{manage ? <ListingForm vehicle={vehicle} owners={owners} features={vehicle.features.map(f => f.feature.name).join(", ")} /> : <p className="text-silver">{vehicle.description}</p>}</Panel>
    <Panel title="Photos and compliance evidence"><p className="mb-5 text-silver">Upload a vehicle photo, registration, insurance and ownership/lease authorization. Images must pass the security scanner before review or publication.</p><div className="mb-6 space-y-3">{files.map(f => <p key={f.id} className="text-sm text-silver"><a className="text-gold-bright underline" href={`/api/marketplace/files/${f.id}`} target="_blank" rel="noreferrer">{f.purpose.replaceAll("_", " ")}</a> · {f.scanStatus}</p>)}</div>{manage && <ActionForm endpoint="/api/host/files" multipart values={{ vehicleId: id }} label="Upload file" fields={[{ name: "purpose", label: "File purpose", options: ["LISTING_PHOTO", "OWNERSHIP", "REGISTRATION", "INSURANCE"] }, { name: "file", label: "Image (JPG, PNG or WebP, max 8 MB)", type: "file" }]} />}</Panel>
    <Panel title="Host Vehicle Listing and Management Agreement">{!legal || legal.needsAttorneyReview ? <p className="text-gold-bright">NOT APPROVED FOR PRODUCTION — TEXAS ATTORNEY REVIEW REQUIRED</p> : <><p className="mb-3 text-silver">Version {legal.version}</p><pre className="mb-6 whitespace-pre-wrap font-sans text-sm text-silver">{legal.content}</pre>{role === "OWNER" && <ActionForm endpoint={`/api/host/vehicles/${id}/agreement`} values={{ version: legal.version }} label="Sign listing agreement" fields={[{ name: "signerName", label: "Full legal name" }]}><label className="text-sm text-silver sm:col-span-2"><input type="checkbox" name="accept" required value="yes" /> I have read and accept this version of the agreement for this vehicle.</label></ActionForm>}</>}{vehicle.agreementAcceptances.map(a => <p key={a.id} className="mt-4"><a href={`/api/host/vehicles/${id}/agreement?acceptanceId=${a.id}`} className="text-gold-bright underline">Download signed {a.documentVersion} agreement</a></p>)}</Panel>
    <Panel title="Availability calendar"><AvailabilityCalendar vehicleId={id} month={month} zone={zone} periods={[...vehicle.blocks.map(b => ({ start: b.startAt, end: b.endAt, label: b.reason })), ...reservations.map(r => ({ start: r.pickupAt, end: r.returnAt, label: r.confirmationNumber }))]} /><div className="mb-5 space-y-4">{vehicle.blocks.map(b => <div key={b.id} className="flex flex-wrap items-center justify-between gap-3 text-sm text-silver"><p>{b.startAt.toISOString().slice(0, 10)} → {b.endAt.toISOString().slice(0, 10)} · {b.reason}</p>{manage && <ActionForm action="unblock" values={{ id: b.id, vehicleId: id }} label="Remove block" />}</div>)}{!vehicle.blocks.length && <p className="text-silver">No blocked dates.</p>}</div>{manage && <div className="space-y-8"><ActionForm action="availability" values={{ vehicleId: id, isBookable: !vehicle.availability?.isBookable }} label={vehicle.availability?.isBookable ? "Pause new bookings" : "Enable approved listing"} /><ActionForm action="block" values={{ vehicleId: id }} label="Block dates" fields={[{ name: "startAt", label: "Block start (your local time)", type: "datetime-local" }, { name: "endAt", label: "Block end (your local time)", type: "datetime-local" }, { name: "reason", label: "Reason", options: ["MAINTENANCE", "OWNER_REQUEST", "OTHER"] }, { name: "notes", label: "Notes", required: false }]} /></div>}</Panel>
    <Panel title="Maintenance">{vehicle.maintenanceRecords.map(m => <p key={m.id} className="mb-3 text-silver">{m.serviceDate.toISOString().slice(0, 10)} · {m.service} · {m.mileage.toLocaleString()} miles</p>)}{manage && <ActionForm action="maintenance" values={{ vehicleId: id }} label="Record maintenance" fields={[{ name: "service", label: "Service", options: ["OIL_CHANGE", "TIRES", "BRAKES", "INSPECTION", "REGISTRATION", "INSURANCE", "REPAIR", "CLEANING", "OTHER"] }, { name: "serviceDate", label: "Service date", type: "date" }, { name: "mileage", label: "Odometer", type: "number", min: 0 }, { name: "costCents", label: "Cost ($)", type: "money", min: 0 }, { name: "nextServiceDate", label: "Next service date", type: "date" }, { name: "notes", label: "Service notes", required: false }]} />}</Panel>
  </Workspace>;
}
