import { ConversationLive } from "@/components/marketplace/conversation-live";
import Link from "next/link";
import { auth } from "@/auth";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { readConversation } from "@/lib/conversations";
import { Workspace, Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{before?:string}>}) {
 const {id}=await params, user=(await auth())!.user!, {before}=await searchParams;
 const data=await readConversation(user.id,id,before).catch(()=>null); if(!data) notFound();
 const files=await prisma.collaborationFile.findMany({where:{conversationId:id,scanStatus:"CLEAN",deletedAt:null},select:{id:true,purpose:true}});
 return <Workspace eyebrow="Private conversation" title="Trip messages" description="Only current participants and authorized support can view this conversation.">{!before && <ConversationLive id={id} messageId={data.messages[0]?.id}/>}<Panel title="Messages"><ol className="space-y-4">{[...data.messages].reverse().map(m=><li key={m.id} className={`max-w-xl rounded-xl border border-white/10 p-4 ${m.senderId===user.id ? "ml-auto bg-gold/10" : "bg-white/5"}`}><p className="text-xs text-gold">{m.senderId===user.id ? "You" : m.senderLabel} · {m.createdAt.toLocaleString("en-US")}{m.editedAt && " · edited"}</p><p className="mt-2 whitespace-pre-wrap break-words">{m.deletedAt ? "Message removed" : m.body}</p><p className="mt-2 text-xs text-silver">Read by {data.reads.filter(r=>r.userId!==m.senderId && r.readAt>=m.createdAt).length} other participants</p>{!m.deletedAt && <details className="mt-3 text-sm"><summary className="cursor-pointer text-silver">Message actions</summary><ActionForm endpoint="/api/community" action="message" values={{id,messageId:m.id,version:m.version}} fields={[{name:"command",label:"Action",options:m.senderId===user.id ? ["edit","delete","report"] : ["report"]},{name:"body",label:"Updated message or report reason",type:"textarea",value:m.body}]} /></details>}</li>)}</ol>{!data.messages.length && <p className="text-silver">Start the conversation below.</p>}{data.messages.length===30 && <Link className="mt-4 inline-block text-gold" href={`?before=${data.messages.at(-1)!.id}`}>Older messages</Link>}<p className="mt-4 text-xs text-silver">{data.reads.filter(r=>r.userId!==user.id).length ? "Read receipts available from other participants." : "Not yet marked read by another participant."}</p><ActionForm endpoint="/api/community" action="message" values={{id,command:"read"}} label="Mark conversation read" /></Panel>{data.history.length>0 && <Panel title="Operator audit history"><ol className="space-y-3">{data.history.map(h=><li className="break-words border-l-2 border-gold/50 pl-3" key={h.id}><p className="text-xs text-gold">{h.action} · Version {h.version} · {h.createdAt.toLocaleString("en-US")}</p><p className="whitespace-pre-wrap text-silver">{h.body || "Soft deletion recorded"}</p></li>)}</ol></Panel>}<Panel title="Write a message"><ActionForm endpoint="/api/community" action="message" values={{id,command:"send"}} fields={[{name:"body",label:"Message",type:"textarea"}]} label="Send message" /></Panel><Panel title="Private attachments"><p className="mb-4 text-sm text-silver">Images only, up to 8 MB. All uploads require a clean security scan. Do not upload identity documents here.</p>{files.map(f=><a className="mb-3 block text-gold" href={`/api/community/files/${f.id}`} key={f.id}>View {f.purpose.toLowerCase()} attachment</a>)}<ActionForm endpoint="/api/community" multipart values={{conversationId:id,purpose:"MESSAGE"}} fields={[{name:"file",label:"Image",type:"file"}]} label="Upload attachment" /></Panel></Workspace>;
}
