import { beforeAll,afterAll,it,expect } from "vitest";
import { spawn,type ChildProcess } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { createServer,type Server } from "node:net";
import { chromium,type Browser,type Page } from "playwright";
import { encode } from "next-auth/jwt";
import sharp from "sharp";
import { prisma,createTestHost,createTestCustomer,createTestVehicle,createTestReservation,cleanupReservationsForVehicles } from "./helpers/factories";
let child:ChildProcess,browser:Browser,scanner:Server;
const base="http://127.0.0.1:3203",secret="community-browser-only-secret",users:string[]=[],hosts:string[]=[],vehicles:string[]=[];
const capture="test-artifacts/community";
beforeAll(async()=>{
 await mkdir(capture,{recursive:true});
 scanner=createServer(socket=>{let bytes=Buffer.alloc(0),framed=false;socket.on("data",chunk=>{bytes=Buffer.concat([bytes,chunk]);if(!framed){const end=bytes.indexOf(0);if(end<0)return;bytes=bytes.subarray(end+1);framed=true;}while(bytes.length>=4){const n=bytes.readUInt32BE(0);if(bytes.length<4+n)return;bytes=bytes.subarray(4+n);if(!n){socket.end("stream: OK\0");return;}}});});
 await new Promise<void>(resolve=>scanner.listen(0,"127.0.0.1",resolve));
 child=spawn(process.execPath,["tests/helpers/app-server.mjs"],{stdio:"inherit",env:{...process.env,BROWSER_TEST_PORT:"3203",NODE_ENV:"development",AUTH_SECRET:secret,AUTH_TRUST_HOST:"true",AUTH_URL:base,NEXTAUTH_URL:base,CLAMAV_HOST:"127.0.0.1",CLAMAV_PORT:String((scanner.address() as {port:number}).port),STRIPE_SECRET_KEY:"",NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:"",STRIPE_WEBHOOK_SECRET:""}});
 let ready=false;for(let i=0;i<240;i++){try{await fetch(base+"/api/auth/session");ready=true;break;}catch{await new Promise(r=>setTimeout(r,500));}}if(!ready)throw new Error("Next server unavailable");browser=await chromium.launch({headless:true});
},150000);
afterAll(async()=>{await browser?.close();if(child&&child.exitCode===null){const done=new Promise(r=>child.once("exit",r));child.kill();await Promise.race([done,new Promise(r=>setTimeout(r,3000))]);}if(scanner)await new Promise<void>(r=>scanner.close(()=>r()));});
afterAll(async()=>{
 const cs=await prisma.serviceCase.findMany({where:{openedById:{in:users}}});const ids=cs.map(c=>c.id);
 const conv=await prisma.conversation.findMany({where:{customerId:{in:users}}});const cids=conv.map(c=>c.id);
 const messages=await prisma.conversationMessage.findMany({where:{conversationId:{in:cids}}});
 await prisma.storageDeletionJob.deleteMany({where:{fileId:{in:(await prisma.collaborationFile.findMany({where:{uploadedById:{in:users}}})).map(f=>f.id)}}});
 await prisma.collaborationFile.deleteMany({where:{uploadedById:{in:users}}});
 await prisma.messageRevision.deleteMany({where:{messageId:{in:messages.map(m=>m.id)}}});
 await prisma.conversationMessage.deleteMany({where:{conversationId:{in:cids}}});await prisma.conversationRead.deleteMany({where:{conversationId:{in:cids}}});await prisma.conversation.deleteMany({where:{id:{in:cids}}});
 await prisma.serviceCaseEvent.deleteMany({where:{caseId:{in:ids}}});await prisma.serviceCase.updateMany({where:{id:{in:ids}},data:{linkedCaseId:null}});await prisma.serviceCase.deleteMany({where:{id:{in:ids}}});
 const reviews=await prisma.tripReview.findMany({where:{reviewerId:{in:users}}});await prisma.reviewHistory.deleteMany({where:{reviewId:{in:reviews.map(r=>r.id)}}});await prisma.tripReview.deleteMany({where:{id:{in:reviews.map(r=>r.id)}}});
 await prisma.inboxNotice.deleteMany({where:{userId:{in:users}}});await prisma.communityReport.deleteMany({where:{actorId:{in:users}}});
 for(const userId of users)await prisma.outboxMessage.deleteMany({where:{payload:{path:["userId"],equals:userId}}});
 await cleanupReservationsForVehicles(vehicles);await prisma.auditLog.deleteMany({where:{actorId:{in:users}}});await prisma.hostEmployee.deleteMany({where:{hostId:{in:hosts}}});await prisma.vehicle.deleteMany({where:{id:{in:vehicles}}});await prisma.hostProfile.deleteMany({where:{id:{in:hosts}}});await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect();
});

async function login(u:{id:string;email:string;role:string}){const ctx=await browser.newContext();const token=await encode({token:{id:u.id,sub:u.id,email:u.email,role:u.role},secret,salt:"authjs.session-token"});await ctx.addCookies([{name:"authjs.session-token",value:token,url:base,httpOnly:true,sameSite:"Lax"}]);return ctx.newPage();}
async function fixture(){const h=await createTestHost(),customer=await createTestCustomer(),agent=await createTestCustomer({role:"CLAIMS_AGENT"}),support=await createTestCustomer({role:"SUPPORT_AGENT"});users.push(h.user.id,customer.id,agent.id,support.id);hosts.push(h.hostProfile.id);const v=await createTestVehicle({hostId:h.hostProfile.id,listingApproval:"APPROVED"});vehicles.push(v.id);const r=await createTestReservation({vehicleId:v.id,customerId:customer.id,pickupAt:new Date(Date.now()-86400000),returnAt:new Date(),status:"COMPLETED"});await prisma.trip.create({data:{reservationId:r.id,startedAt:new Date(Date.now()-86400000),endedAt:new Date()}});return {h,customer,agent,support,v,r};}
async function shot(page:Page,name:string,widths=[390,1440]){await page.getByRole("heading",{level:1}).waitFor();await page.evaluate(()=>document.fonts.ready);for(const width of widths){await page.setViewportSize({width,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path: capture+"/"+name+"-"+width+".png",fullPage:true,animations:"disabled"});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(await page.getByRole("heading",{level:1}).count()).toBe(1);}}
function panel(page:Page,name:string){return page.locator("section:visible").filter({has:page.getByRole("heading",{name,exact:true})});}
async function save(page:Page,name:string,button="Save changes"){const section=panel(page,name);await section.locator('form[data-hydrated="true"]').waitFor();expect(await section.locator("form").evaluate(f=>(f as HTMLFormElement).checkValidity()),"Form must be valid before submission: "+name).toBe(true);const response=page.waitForResponse(r=>r.url().endsWith("/api/community")&&r.request().method()==="POST"&&!r.request().postData()?.includes('"command":"read"'));await section.getByRole("button",{name:button,exact:true}).click();const res=await response;expect(res.status(),await res.text()).toBe(200);await page.waitForLoadState("networkidle");await page.reload();}
async function openCase(page:Page,rid:string,kind:string,title:string,category="DAMAGE"){await page.goto(base+"/connect?view=cases&reservationId="+rid);await page.getByLabel("Request type").selectOption(kind);await page.getByRole("button",{name:"Continue to details"}).click();await page.getByLabel("Category",{exact:true}).selectOption(category);await page.getByLabel("Short summary").fill(title);await page.getByLabel("What happened?").fill("Detailed synthetic browser evidence for the requested workflow.");if(kind==="CLAIM"||kind==="INCIDENT")await page.getByLabel("Location / damaged area").fill("Synthetic trip location");if(kind==="INCIDENT")await page.getByLabel("Incident date and time").fill("2026-09-17T10:00");await page.getByRole("button",{name:"Open request",exact:true}).click();await page.waitForURL(/\/connect\/cases\/[^/]+$/);return page.url().split("/").at(-1)!;}
async function assign(page:Page,id:string,userId:string){await page.goto(base+"/connect/cases/"+id);await page.getByLabel("Authorized agent ID").fill(userId);await page.getByLabel("Assignment or conflict reason").fill("Assigned after confirming no conflict of interest.");await save(page,"Assignment & escalation");}
async function transition(page:Page,state:string){await page.reload();await page.getByLabel("Next state").selectOption(state);await page.getByLabel("Reason / decision").fill("Reviewed the submitted evidence and party responses. No payment is authorized.");await save(page,"Next step","Submit next step");}
it("real customer-host messaging, private attachment, notifications and all target viewport widths",async()=>{
 const f=await fixture(),customer=await login(f.customer),host=await login(f.h.user);await customer.goto(base+"/account/reservations/"+f.r.id);await customer.getByRole("button",{name:"Message trip participants"}).click();await customer.waitForURL(/\/connect\/conversations\/[^/]+$/);const url=customer.url();
 await customer.getByLabel("Message",{exact:true}).fill("The pickup instructions are clear. Thank you.");await save(customer,"Write a message","Send message");await host.goto(url);await host.locator("p:visible").filter({hasText:"The pickup instructions are clear. Thank you."}).waitFor();await host.getByLabel("Message",{exact:true}).fill("You are welcome. The agreed meeting point is ready.");await save(host,"Write a message","Send message");
 const image=await sharp({create:{width:24,height:24,channels:3,background:"silver"}}).png().toBuffer();await panel(host,"Private attachments").locator('form[data-hydrated="true"]').waitFor();await panel(host,"Private attachments").getByLabel("Image",{exact:true}).setInputFiles({name:"pickup.png",mimeType:"image/png",buffer:image});await save(host,"Private attachments","Upload attachment");await host.getByRole("link",{name:"View message attachment"}).waitFor();await shot(host,"conversation",[375,390,430,768,1024,1440]);await customer.goto(base+"/connect?view=notifications");await customer.getByRole("link",{name:/New private message/}).first().waitFor();await shot(customer,"notifications");
},120000);
it("real mutual post-trip reviews remain blind and never expose private customer reputation publicly",async()=>{
 const f=await fixture();for(const [u,subject]of [[f.customer,"VEHICLE"],[f.h.user,"CUSTOMER"]] as const){const p=await login(u);await p.goto(base+"/connect?view=reviews&reservationId="+f.r.id);await p.getByLabel("Review subject").selectOption(subject);await p.getByLabel("Your experience").fill("A thoughtful and punctual trip participant.");await save(p,"Write a review");await shot(p,"review-"+subject.toLowerCase());}expect(await prisma.tripReview.count({where:{reservationId:f.r.id}})).toBe(2);expect(await prisma.tripReview.count({where:{reservationId:f.r.id,publishAfter:{lte:new Date()}}})).toBe(0);
},120000);
it("real host claim, customer response and claims-agent resolution retain financial review",async()=>{
 const f=await fixture(),host=await login(f.h.user),customer=await login(f.customer),agent=await login(f.agent);const id=await openCase(host,f.r.id,"CLAIM","Browser damage claim");const image=await sharp({create:{width:24,height:24,channels:3,background:"gold"}}).png().toBuffer();await panel(host,"Evidence").locator('form[data-hydrated="true"]').waitFor();await host.getByLabel("Evidence image").setInputFiles({name:"damage.png",mimeType:"image/png",buffer:image});await save(host,"Evidence","Upload evidence");await transition(host,"EVIDENCE_SUBMITTED");await assign(agent,id,f.agent.id);await transition(agent,"INITIAL_REVIEW");await transition(agent,"CUSTOMER_RESPONSE");await customer.goto(base+"/connect/cases/"+id);await customer.getByLabel("Response",{exact:true}).fill("Please compare the original pickup inspection evidence.");await save(customer,"Respond","Send response");await shot(customer,"claim-timeline");for(const state of ["ESTIMATE_REVIEW","RESPONSIBILITY_DECISION","PROPOSED_SETTLEMENT"])await transition(agent,state);await customer.reload();await transition(customer,"ACCEPTED");await transition(agent,"RESOLVED");await transition(agent,"CLOSED");expect(await prisma.reservation.findUnique({where:{id:f.r.id}})).toMatchObject({financialDisposition:"REVIEW"});expect(await prisma.financialOperation.count({where:{reservationId:f.r.id}})).toBe(0);await shot(agent,"claim-resolution");
},180000);
it("real dispute response, decision and appeal preserve immutable decision history",async()=>{
 const f=await fixture(),customer=await login(f.customer),host=await login(f.h.user),agent=await login(f.agent);const id=await openCase(customer,f.r.id,"DISPUTE","Browser fuel dispute","FUEL");await assign(agent,id,f.agent.id);await transition(agent,"RESPONSE_REQUESTED");await host.goto(base+"/connect/cases/"+id);await host.getByLabel("Response",{exact:true}).fill("The return evidence records the fuel gauge reading.");await save(host,"Respond","Send response");await transition(agent,"UNDER_REVIEW");await transition(agent,"DECIDED");await customer.reload();await customer.getByLabel("Reason for appeal and new information").fill("Please consider the additional timestamped return evidence.");await save(customer,"Appeal decision","Submit appeal");expect(await prisma.serviceCaseEvent.count({where:{caseId:id,toState:"DECIDED"}})).toBe(1);await shot(customer,"dispute-appeal");await agent.goto(base+"/connect?view=operations");await shot(agent,"operations");
},180000);
it("real roadside incident blocks bookings and support ticket receives an agent reply",async()=>{
 const f=await fixture(),customer=await login(f.customer),support=await login(f.support);const incident=await openCase(customer,f.r.id,"INCIDENT","Unsafe vehicle reported","UNSAFE_VEHICLE");expect(await prisma.vehicle.findUnique({where:{id:f.v.id}})).toMatchObject({status:"MAINTENANCE"});await shot(customer,"incident");await assign(support,incident,f.support.id);await transition(support,"TRIAGED");const ticket=await openCase(customer,f.r.id,"TICKET","Help with a reservation","GENERAL");await assign(support,ticket,f.support.id);await support.getByLabel("Response",{exact:true}).fill("We have received your question and reviewed the reservation.");await save(support,"Respond","Send response");await customer.reload();await customer.locator("p:visible").filter({hasText:"We have received your question and reviewed the reservation."}).waitFor();await shot(customer,"support-ticket");await customer.goto(base+"/connect?view=support");await shot(customer,"support-center",[375,390,430,768,1024,1440]);
},180000);
