import { afterEach,expect,it,vi } from "vitest";
import type { FinancialOperation } from "@prisma/client";
const api=vi.hoisted(()=>({accounts:{create:vi.fn(),retrieve:vi.fn()},balance:{retrieve:vi.fn()}}));
vi.mock("stripe",()=>({default:class {accounts=api.accounts;balance=api.balance;}}));
import { accountProjection,createFinanceProviderObject,verifyFinanceDestination } from "@/lib/finance-provider";
const operation=(kind="FINANCE_TRANSFER")=>({id:"op_fixture",key:"transfer:fixture",kind,payload:{hostId:"host_fixture",batchId:"batch_fixture",accountId:"acct_fixture",amount:5000,currency:"usd"}} as unknown as FinancialOperation);
const account=()=>({id:"acct_fixture",metadata:{hostId:"host_fixture",operationKey:"connect:host_fixture"},payouts_enabled:true,details_submitted:true,requirements:{currently_due:[],disabled_reason:null},settings:{payouts:{schedule:{interval:"manual"}}},company:{tax_id_provided:true},external_accounts:{data:[{account_number:"secret-bank"}]},individual:{id_number:"secret-ssn"}});
afterEach(()=>{vi.unstubAllEnvs();vi.clearAllMocks();});
function sandbox(){vi.stubEnv("FINANCE_SANDBOX_ENABLED","true");vi.stubEnv("STRIPE_SECRET_KEY","sk_test_fixture");}
it("Connect creation requests provider-hosted collection and platform-controlled manual payouts",async()=>{sandbox();api.accounts.create.mockResolvedValue(account());await createFinanceProviderObject(operation("FINANCE_CONNECT"),"connect:host_fixture");expect(api.accounts.create).toHaveBeenCalledWith(expect.objectContaining({controller:{fees:{payer:"application"},losses:{payments:"application"},stripe_dashboard:{type:"express"},requirement_collection:"stripe"},settings:{payouts:{schedule:{interval:"manual"}}}}),{idempotencyKey:"connect:host_fixture"});});
it("provider projection retains safe status without banking or taxpayer secrets",()=>{const result=accountProjection(account() as never);expect(result.taxStatus).toBe("VERIFIED");expect(JSON.stringify(result)).not.toMatch(/secret-bank|secret-ssn|external_accounts|id_number/);});
it("dispatch checks current provider ownership, manual controls and available balance",async()=>{sandbox();api.accounts.retrieve.mockResolvedValue(account());api.balance.retrieve.mockResolvedValue({available:[{currency:"usd",amount:4999}]});await expect(verifyFinanceDestination(operation())).rejects.toThrow("balance");api.balance.retrieve.mockResolvedValue({available:[{currency:"usd",amount:5000}]});await expect(verifyFinanceDestination(operation())).resolves.toBeUndefined();api.accounts.retrieve.mockResolvedValue({...account(),metadata:{hostId:"another_host"}});await expect(verifyFinanceDestination(operation())).rejects.toThrow("ownership");});
it("live keys cannot enable real finance movement",async()=>{sandbox();vi.stubEnv("STRIPE_SECRET_KEY","sk_live_fixture");await expect(createFinanceProviderObject(operation("FINANCE_CONNECT"),"connect:host_fixture")).rejects.toThrow("live payouts are disabled");expect(api.accounts.create).not.toHaveBeenCalled();});

it("Connect country is taken from the persisted request rather than changing runtime configuration",async()=>{sandbox();vi.stubEnv("STRIPE_CONNECT_COUNTRY","GB");api.accounts.create.mockResolvedValue(account());const op=operation("FINANCE_CONNECT");op.payload={hostId:"host_fixture",country:"US"};await createFinanceProviderObject(op,"connect:host_fixture");expect(api.accounts.create).toHaveBeenCalledWith(expect.objectContaining({country:"US"}),{idempotencyKey:"connect:host_fixture"});});
