import { afterAll,afterEach,describe,it,expect,vi } from "vitest";
import { PrismaClient } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { createDeviceSession,validateDeviceSession,revokeDeviceSessions,rotateDeviceSession } from "@/lib/device-sessions";
import { claimOperations,finishOperation } from "@/lib/operations";
import { requestOriginAllowed,authenticatedCron,sharedRequestLimit } from "@/lib/security-request";
import { requireReleaseFeature } from "@/lib/release-control";
import { storePrivateDocument,readPrivateDocument,deletePrivateDocument } from "@/lib/storage";
import { safeLog } from "@/lib/safe-log";
import { createTestCustomer,prisma } from "./helpers/factories";
const other=new PrismaClient(),users:string[]=[],keys:string[]=[];
afterEach(()=>vi.unstubAllEnvs());
afterAll(async()=>{await prisma.operationsJob.deleteMany({where:{key:{in:keys}}});await prisma.auditLog.deleteMany({where:{actorId:{in:users}}});await prisma.user.deleteMany({where:{id:{in:users}}});await other.$disconnect();await prisma.$disconnect();});
async function actor(){const user=await createTestCustomer();users.push(user.id);return user;}
describe("database-authoritative device sessions",()=>{
 it("revokes one device without revoking another, then revokes all",async()=>{const user=await actor(),a=await createDeviceSession(user.id),b=await createDeviceSession(user.id);expect(await validateDeviceSession(user.id,a.sid,0)).not.toBeNull();await revokeDeviceSessions(user.id,a.sid);expect(await validateDeviceSession(user.id,a.sid,0)).toBeNull();expect(await validateDeviceSession(user.id,b.sid,0)).not.toBeNull();await revokeDeviceSessions(user.id);expect(await validateDeviceSession(user.id,b.sid,0)).toBeNull();});
 it("cannot revoke another user's session",async()=>{const a=await actor(),b=await actor(),session=await createDeviceSession(b.id);expect(await revokeDeviceSessions(a.id,session.sid)).toBe(0);expect(await validateDeviceSession(b.id,session.sid,0)).not.toBeNull();});
 it("rejects suspended, idle and absolutely expired sessions",async()=>{const user=await actor(),session=await createDeviceSession(user.id);await prisma.user.update({where:{id:user.id},data:{isActive:false}});expect(await validateDeviceSession(user.id,session.sid,0)).toBeNull();await prisma.user.update({where:{id:user.id},data:{isActive:true}});await prisma.session.update({where:{id:session.sid},data:{lastSeenAt:new Date(Date.now()-31*60000)}});expect(await validateDeviceSession(user.id,session.sid,0)).toBeNull();await prisma.session.update({where:{id:session.sid},data:{lastSeenAt:new Date(),expires:new Date(0)}});expect(await validateDeviceSession(user.id,session.sid,0)).toBeNull();});
 it("rejects expired step-up without rotating credentials",async()=>{const user=await actor(),s=await createDeviceSession(user.id);const bcrypt=await import("bcryptjs");await prisma.authCode.create({data:{email:user.email,purpose:"SECURITY_STEP_UP",codeHash:await bcrypt.hash("123456",4),expiresAt:new Date(0)}});await expect(rotateDeviceSession(user.id,s.sid,0,"123456")).rejects.toThrow("REAUTHENTICATION_REQUIRED");expect(await validateDeviceSession(user.id,s.sid,0)).not.toBeNull();await prisma.authCode.deleteMany({where:{email:user.email}});});
 it("purpose-bound reauthentication rotates once and invalidates the prior cookie",async()=>{const user=await actor(),s=await createDeviceSession(user.id);const bcrypt=await import("bcryptjs");await prisma.authCode.create({data:{email:user.email,purpose:"SECURITY_STEP_UP",codeHash:await bcrypt.hash("123456",4),expiresAt:new Date(Date.now()+60000)}});expect(await rotateDeviceSession(user.id,s.sid,0,"123456")).toBe(1);expect(await validateDeviceSession(user.id,s.sid,0)).toBeNull();expect(await validateDeviceSession(user.id,s.sid,1)).not.toBeNull();await expect(rotateDeviceSession(user.id,s.sid,1,"123456")).rejects.toThrow();await prisma.authCode.deleteMany({where:{email:user.email}});});
 it("observes committed suspension after waiting on a separate PostgreSQL connection",async()=>{
  const user=await actor(),s=await createDeviceSession(user.id);let release!:()=>void,locked!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>locked=r);
  const suspend=other.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id=${user.id} FOR UPDATE`;await tx.user.update({where:{id:user.id},data:{isActive:false}});locked();await gate;},{timeout:15000});await ready;
  const validation=validateDeviceSession(user.id,s.sid,0);
  let waiting=false;for(let i=0;i<50;i++){const rows=await prisma.$queryRaw<Array<{n:bigint}>>`SELECT count(*) AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE '%User%FOR UPDATE%'`;if(Number(rows[0].n)>0){waiting=true;break;}await new Promise(r=>setTimeout(r,20));}release();await suspend;expect(waiting).toBe(true);expect(await validation).toBeNull();
 });
});
describe("operational fencing",()=>{
 it("claims each job once across separate simultaneous database connections and rejects stale completion",async()=>{
  const kind="TEST_"+randomUUID();for(let i=0;i<10;i++){const key=kind+i;keys.push(key);await prisma.operationsJob.create({data:{key,kind}});}
  let release!:()=>void;const barrier=new Promise<void>(r=>release=r);
  const a=(async()=>{await barrier;return claimOperations(kind,prisma);})(),b=(async()=>{await barrier;return claimOperations(kind,other);})();release();const groups=await Promise.all([a,b]);const rows=groups.flat();expect(rows).toHaveLength(10);expect(new Set(rows.map(r=>r.key)).size).toBe(10);
  const stale=rows[0];await prisma.operationsJob.update({where:{key:stale.key},data:{leaseExpiresAt:new Date(0)}});const reclaimed=(await claimOperations(kind,other))[0];expect(reclaimed.leaseToken).not.toBe(stale.leaseToken);expect((await finishOperation(stale,"DONE",undefined,prisma)).count).toBe(0);expect((await finishOperation(reclaimed,"DONE",undefined,other)).count).toBe(1);
 });
 it("enforces one shared rate budget across concurrent clients",async()=>{const scope=randomUUID(),headers=new Headers({"x-real-ip":"synthetic"});expect((await Promise.all(Array.from({length:8},()=>sharedRequestLimit(headers,scope,3)))).filter(Boolean)).toHaveLength(3);});
});
describe("storage and request boundaries",()=>{
 it("verifies content hashes, rejects path traversal, quarantined and infected objects",async()=>{const id=randomUUID(),bytes=Buffer.from("synthetic private fixture"),stored=await storePrivateDocument(bytes,"application/pdf",id);expect((await readPrivateDocument(stored.storageKey)).buffer.equals(bytes)).toBe(true);await writeFile(`private-storage/documents/${id}.pdf`,Buffer.from("tampered"));await expect(readPrivateDocument(stored.storageKey)).rejects.toThrow("INTEGRITY");await prisma.privateObject.update({where:{key:stored.storageKey},data:{state:"INFECTED"}});await expect(readPrivateDocument(stored.storageKey)).rejects.toThrow("NOT_CLEAN");await prisma.privateObject.update({where:{key:stored.storageKey},data:{state:"QUARANTINED"}});await expect(readPrivateDocument(stored.storageKey)).rejects.toThrow("NOT_CLEAN");await expect(readPrivateDocument("local:../../outside.txt")).rejects.toThrow();await deletePrivateDocument(stored.storageKey);});
 it("fails closed on deployed origins, cron authentication, unsafe flags and local fixtures",async()=>{vi.stubEnv("APP_ENV","staging");vi.stubEnv("NODE_ENV","development");vi.stubEnv("SITE_URL","https://staging.renta4wheel.com");vi.stubEnv("CRON_SECRET","a".repeat(40));expect(requestOriginAllowed(new Request("https://staging.renta4wheel.com/api/a",{method:"POST"}))).toBe(false);expect(requestOriginAllowed(new Request("https://staging.renta4wheel.com/api/a",{headers:{origin:"https://evil.invalid"}}))).toBe(false);expect(authenticatedCron(new Headers({authorization:"Bearer incorrect"}))).toBe(false);expect(authenticatedCron(new Headers({authorization:"Bearer "+"a".repeat(40)}))).toBe(true);await expect(requireReleaseFeature("booking")).rejects.toThrow("FEATURE_NOT_RELEASED");await expect(requireReleaseFeature("live_charges")).rejects.toThrow();await expect(storePrivateDocument(Buffer.from("fixture"),"application/pdf")).rejects.toThrow("PRIVATE_STORAGE_UNAVAILABLE");});
 it("never logs exception contents or untrusted metadata",()=>{const spy=vi.spyOn(console,"error").mockImplementation(()=>{});safeLog("AUTH_FAILED",new Error("secret code 123456 license bank payload"),"invalid token value");expect(JSON.stringify(spy.mock.calls)).not.toMatch(/123456|license|bank|payload|token value/);spy.mockRestore();});
});
