import { prisma } from "@/lib/prisma";
import { hostFinancePage } from "@/lib/finance-page-access";
import { FinanceWorkspace,FinanceRestricted,FinanceEmpty } from "@/components/marketplace/finance-workspace";
import { Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
export default async function StatementsPage(){const context=await hostFinancePage();if(!context)return <FinanceRestricted/>;
 const rows=await prisma.financeDocument.findMany({where:{hostId:context.host.id,kind:{in:["EARNINGS_STATEMENT","PAYOUT_STATEMENT","ADJUSTMENT_STATEMENT","MONTHLY_SUMMARY","YEARLY_SUMMARY"]}},select:{id:true,kind:true,version:true,createdAt:true,currency:true},orderBy:{createdAt:"desc"},take:100});
 return <FinanceWorkspace title="Financial statements" description="Private, versioned records. An issued PDF remains unchanged; a fresh snapshot creates a new version."><div className="grid gap-6 lg:grid-cols-2"><Panel title="Monthly or yearly summary"><ActionForm endpoint="/api/finance" action="document" fields={[{name:"kind",label:"Statement",options:["MONTHLY_SUMMARY","YEARLY_SUMMARY"]},{name:"period",label:"Period (YYYY-MM or YYYY)",value:new Date().toISOString().slice(0,7)}]} values={{newVersion:true}} redirectTo="/api/finance/documents/:id" label="Issue summary PDF"/><p className="mt-5 text-sm text-silver">These summaries are financial information. Final 1099 eligibility and filing require tax-professional/provider confirmation.</p></Panel><Panel title="Reservation statement"><ActionForm endpoint="/api/finance" action="document" fields={[{name:"kind",label:"Statement",options:["EARNINGS_STATEMENT","ADJUSTMENT_STATEMENT"]},{name:"reservationId",label:"Reservation ID"}]} values={{newVersion:true}} redirectTo="/api/finance/documents/:id" label="Issue reservation PDF"/></Panel></div><Panel title="Issued documents">{rows.length?<div className="divide-y divide-white/10">{rows.map(d=><a key={d.id} href={`/api/finance/documents/${d.id}`} className="flex flex-wrap justify-between gap-3 py-4 text-sm text-gold-bright"><span>{d.kind.replaceAll("_"," ")} · version {d.version}</span><span>{d.createdAt.toLocaleDateString()} · {d.currency.toUpperCase()} · PDF ↓</span></a>)}</div>:<FinanceEmpty>No statements issued yet. Choose a period or reservation above.</FinanceEmpty>}</Panel></FinanceWorkspace>;
}
