import {JurisdictionPanel} from "@/components/admin/jurisdiction-panel";
import {JURISDICTION_GATES} from "@/lib/jurisdiction";
import {auth} from "@/auth";
import {redirect} from "next/navigation";
import {prisma} from "@/lib/prisma";
import {productionConfiguration} from "@/lib/production-config";
import {operationalMetrics} from "@/lib/operations";
import {FEATURES,POLICY_KINDS} from "@/lib/release-control";
import {OperationsPanel} from "@/components/admin/operations-panel";
export default async function OperationsPage(){const session=await auth();if(session?.user?.role!=="SUPER_ADMIN")redirect("/account");const config=productionConfiguration(),metrics=await operationalMetrics(),flags=await prisma.releaseFeature.findMany(),policies=await prisma.policyApproval.findMany({where:{effectiveAt:{lte:new Date()}},orderBy:[{effectiveAt:"desc"},{createdAt:"desc"}],select:{kind:true,version:true,jurisdiction:true,status:true}});const states=await prisma.jurisdiction.findMany({orderBy:{code:"asc"}}),gates=await prisma.jurisdictionApproval.findMany({where:{effectiveAt:{lte:new Date()}},orderBy:{version:"desc"}});const stateRows=states.map(s=>({...s,readyGates:JURISDICTION_GATES.filter(category=>{const gate=gates.find(g=>g.jurisdictionCode===s.code&&g.category===category);return gate?.status==="STAGING_READY"&&gate.reviewedAt&&gate.reviewedById&&(!gate.endsAt||gate.endsAt>new Date());}).length}));return <main className="mx-auto max-w-5xl space-y-8 p-6"><h1 className="text-3xl font-semibold">Production readiness</h1><section><h2 className="text-xl font-semibold">Configuration: {config.ready?"syntax validated":"incomplete"}</h2><p>Environment: {config.environment}. Live finance disabled. Provider health and legal approval are separate gates.</p><ul>{config.issues.map((i,index)=><li key={index}>{i.field}: {i.code}</li>)}</ul></section><section><h2 className="text-xl font-semibold">Recovery queues</h2><dl>{Object.entries(metrics).map(([key,value])=><div className="flex gap-3" key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p>Uncertain money movement requires finance reconciliation. Failed scans and deletions require the operations runbook.</p></section><JurisdictionPanel states={stateRows}/><OperationsPanel flags={FEATURES.map(key=>({key,enabled:flags.some(f=>f.key===key&&f.enabled)}))}/><section><h2 className="text-xl font-semibold">Professional approval registry</h2><ul>{POLICY_KINDS.map(kind=><li key={kind}>{kind}: {policies.filter((p,index)=>p.kind===kind&&policies.findIndex(v=>v.kind===p.kind&&v.jurisdiction===p.jurisdiction)===index).map(p=>`${p.jurisdiction}: ${p.version} (${p.status})`).join(", ")||"Not approved — professional review required"}</li>)}</ul></section></main>;}

