import { CommunityRecoveryPanels } from "./community-recovery-panels";
import { prisma } from "@/lib/prisma";
import { Panel } from "./workspace";
import { ActionForm } from "./action-form";
import { policy } from "@/lib/collaboration-access";
export async function CommunityAdminPanels({role}:{role:string}) {
 if(!["ADMIN","SUPER_ADMIN"].includes(role))return null;
 const p=await policy(prisma),reports=await prisma.communityReport.findMany({where:{status:"OPEN"},take:30,orderBy:{createdAt:"asc"}}),reviews=await prisma.tripReview.findMany({take:30,orderBy:{createdAt:"desc"}}),failures=await prisma.outboxMessage.findMany({where:{status:"FAILED"},take:30,select:{id:true,attempts:true,lastError:true}});
 return <><CommunityRecoveryPanels role={role}/><Panel title="Abuse reports">{reports.length ? reports.map(r=><div key={r.id} className="mb-6"><p>{r.entityType} · {r.reason}</p><ActionForm endpoint="/api/community" action="admin" values={{command:"report",id:r.id}} fields={[{name:"reason",label:"Investigation result"}]} label="Record investigation" /></div>) : <p>No open reports.</p>}</Panel><Panel title="Review moderation">{reviews.map(r=><details key={r.id} className="border-b border-white/10 py-3"><summary>{r.subject} · {r.rating}/5 · {r.hidden ? "Hidden" : "Visible after blind period"}</summary><p className="my-3 whitespace-pre-wrap">{r.body}</p><ActionForm endpoint="/api/community" action="moderate" values={{id:r.id}} fields={[{name:"command",label:"Moderation action",options:["hide","restore"]},{name:"reason",label:"Moderation reason"}]} /></details>)}</Panel><Panel title="Delivery failures">{failures.length ? failures.map(f=><p className="mb-3 break-all text-sm" key={f.id}>Delivery {f.id}: {f.attempts} attempts · {f.lastError ?? "DELIVERY_FAILED"}</p>) : <p>No dead-letter deliveries.</p>}</Panel><Panel title="Response and retention settings"><ActionForm endpoint="/api/community" action="admin" values={{command:"policy"}} fields={[{name:"editMinutes",label:"Message / review edit window (minutes)",type:"number",value:p.editMinutes,min:1,max:60},{name:"reviewDays",label:"Review submission window (days)",type:"number",value:p.reviewDays,min:1,max:90},{name:"blindDays",label:"Blind review period (days)",type:"number",value:p.blindDays,min:1,max:90},{name:"responseHours",label:"Response deadline (hours)",type:"number",value:p.responseHours,min:1,max:720},{name:"retentionDays",label:"Default retention (days)",type:"number",value:p.retentionDays,min:30,max:3650},...(["messageDays","attachmentDays","reviewRetentionDays","claimDays","disputeDays","incidentDays","ticketDays","deliveryDays"] as const).map(name=>({name,label:name.replace(/([A-Z])/g," $1")+" (new records)",type:"number",value:p[name],min:30,max:3650}))]} /></Panel><Panel title="Roadside contacts & response template"><p className="mb-3 text-silver">Enter approved business information. These fields do not establish insurance coverage.</p><ActionForm endpoint="/api/community" action="admin" values={{command:"contacts"}} fields={[{name:"roadside",label:"Roadside contact / instructions",type:"textarea"},{name:"insurance",label:"Insurance contact / instructions",type:"textarea"},{name:"template",label:"Support response template",type:"textarea"}]} /></Panel>{role==="SUPER_ADMIN" && <Panel title="Legal retention hold"><ActionForm endpoint="/api/community" action="admin" values={{command:"hold"}} fields={[{name:"entity",label:"Record type",options:["CASE","CONVERSATION","FILE","REVIEW"]},{name:"id",label:"Record ID"},{name:"held",label:"Legal hold",options:["yes","no"]},{name:"reason",label:"Legal authority and reason",type:"textarea"}]} /></Panel>}</>;
}
