import { prisma } from "@/lib/prisma";
import { Panel } from "./workspace";
import { ActionForm } from "./action-form";
export async function CommunityRecoveryPanels({ role }: { role: string }) {
 if (!["ADMIN", "SUPER_ADMIN"].includes(role)) return null;
 const [channels, deletions, privacy] = await Promise.all([
  prisma.channelDelivery.findMany({where:{state:{in:["REVIEW","DEAD_LETTER","CONFIGURATION_REQUIRED"]}},take:30,orderBy:{createdAt:"asc"},select:{id:true,channel:true,state:true,errorCode:true,attempts:true}}),
  prisma.storageDeletionJob.findMany({where:{state:"DEAD_LETTER"},take:30,orderBy:{createdAt:"asc"},select:{id:true,fileId:true,errorCode:true,attempts:true}}),
  role === "SUPER_ADMIN" ? prisma.privacyDeletion.findMany({where:{reviewedAt:null},take:30,orderBy:{createdAt:"asc"}}) : []
 ]);
 return <><Panel title="SMS and push delivery review"><p className="mb-4 text-sm text-silver">Oldest 30 unresolved records. REVIEW means the provider outcome is uncertain: investigate in the provider console; do not resend. ACCEPTED means provider acceptance, not handset delivery. Push awaits a mobile provider.</p>{channels.length ? channels.map(d=><p key={d.id} className="mb-3 break-all text-sm">{d.channel} · {d.state} · {d.id} · {d.attempts} attempts · {d.errorCode ?? "Provider configuration required"}</p>) : <p>No channel failures.</p>}</Panel><Panel title="Private-storage deletion recovery"><p className="mb-4 text-sm text-silver">Retries use the original immutable storage key and recheck retention authorization. No private storage URLs are exposed.</p>{deletions.length ? deletions.map(d=><div key={d.id} className="mb-5"><p className="break-all text-sm">File {d.fileId} · {d.attempts} attempts · {d.errorCode}</p>{role === "SUPER_ADMIN" && <ActionForm endpoint="/api/community" action="admin" values={{command:"retryDeletion",id:d.id}} fields={[{name:"reason",label:"Recovery investigation and reason"}]} label="Retry exact deletion"/>}</div>) : <p>No dead-letter deletions.</p>}</Panel>{role === "SUPER_ADMIN" && <Panel title="Privacy request review"><p className="mb-4 text-sm text-silver">Recording a review never overrides legal, security, financial or agreement holds. Scheduled retention follows each record’s approved deadline.</p>{privacy.length ? privacy.map(p=><div key={p.id} className="mb-5"><p className="break-all text-sm">Request {p.id} · User {p.userId} · {p.createdAt.toLocaleString("en-US")}</p><ActionForm endpoint="/api/community" action="admin" values={{command:"privacyReview",id:p.id}} fields={[{name:"state",label:"Privacy review outcome",options:["RETAINED_LEGAL_REVIEW","SCHEDULED_RETENTION"]},{name:"reason",label:"Retention authority and investigation",type:"textarea"}]} label="Record privacy review"/></div>) : <p>No pending privacy requests.</p>}</Panel>}</>;
}
