import { CommunitySla } from "@/components/marketplace/community-sla";
import { ReviewWorkspace } from "@/components/marketplace/review-workspace";
import { customerReputation } from "@/lib/trip-reviews";
import { CaseIntake } from "@/components/marketplace/case-intake";
import { CommunityAdminPanels } from "@/components/marketplace/community-admin-panels";
import Link from "next/link";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Workspace, Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
import { conversationAccess } from "@/lib/conversations";
import { caseAccess } from "@/lib/service-cases";
import { collaborationScopes, isOperator } from "@/lib/collaboration-access";
const endpoint = "/api/community";
export default async function Page({ searchParams }: { searchParams: Promise<{ view?: string; q?: string; reservationId?: string; page?: string; customerId?: string }> }) {
 const user = (await auth())!.user!, { view = "inbox", q = "", reservationId = "", page: pageInput = "1", customerId = "" } = await searchParams;
 const page = Math.max(1, Math.min(10000, Number(pageInput) || 1)), scopes = await collaborationScopes(prisma, user.id);
 const actor = await prisma.user.findUniqueOrThrow({ where: { id: user.id } });
 if (view === "notifications") {
  const smsEnrollment = await prisma.smsConsent.findUnique({where:{userId:user.id}});
  const notices = await prisma.inboxNotice.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" }, take: 100 });
  return <Workspace eyebrow="Your account" title="Notification center" description="Important account and legal updates stay available here, regardless of email delivery."><Panel title="Updates">{notices.length ? notices.map(n=><Link className="block border-b border-white/10 py-4" href={`/api/community/notices/${n.id}`} key={n.id}>{!n.readAt && <span className="text-gold">● </span>}{n.title}<span className="block text-xs text-silver">{n.createdAt.toLocaleString("en-US")}</span></Link>) : <p className="text-silver">No updates yet.</p>}</Panel><Panel title="Email preferences"><ActionForm endpoint={endpoint} action="preference" fields={[{name:"category",label:"Category",options:["MESSAGE","CLAIM","DISPUTE","INCIDENT","TICKET","REVIEW","BOOKING","PAYMENT","TRIP","DOCUMENT","AGREEMENT","MAINTENANCE"]},{name:"email",label:"Optional email delivery",options:["on","off"]},{name:"sms",label:"SMS (requires handset consent)",options:["off","on"]}]} /><p className="mt-4 text-sm text-silver">Required transactional and legal notifications cannot be disabled.</p></Panel><Panel title="Text-message consent"><p className="mb-4 text-silver">Optional account texts. Message and data rates may apply. Reply STOP to opt out. After requesting enrollment, send {smsEnrollment?.source.startsWith("PENDING:") ? "START " + smsEnrollment.source.slice(8) : "your account-specific START code"} from that phone to {process.env.TWILIO_FROM_NUMBER ?? "the business number (not yet configured)"} within 24 hours. No texts are sent until that handset confirms.</p><ActionForm endpoint={endpoint} action="smsConsent" fields={[{name:"phone",label:"International phone number (+ country code)"},{name:"consent",label:"I consent to account update texts",options:["no","yes"]}]} label="Request text enrollment" /></Panel></Workspace>;
 }
 if (view === "reputation") { const reviews = await customerReputation(user.id, customerId); return <Workspace eyebrow="Private host view" title="Customer reputation" description="Only authorized hosts with a reservation for this customer can see this feedback."><Panel title="Completed trip feedback">{reviews.length ? reviews.map((r,i)=><blockquote className="mb-5 border-l-2 border-gold pl-4" key={i}><p>{r.rating} / 5</p><p className="whitespace-pre-wrap text-silver">{r.body}</p></blockquote>) : <p>No eligible published customer feedback yet.</p>}</Panel></Workspace>; }
 if (view === "reviews") return <Workspace eyebrow="After your trip" title="Share your experience" description="Reviews stay blind for the configured review period. Customer reputation is private to authorized hosts."><Panel title="Write a review"><ActionForm endpoint={endpoint} action="review" fields={[{name:"reservationId",label:"Reservation ID",value:reservationId},{name:"subject",label:"Review subject",options:["VEHICLE","HOST","CUSTOMER"]},... ["rating","cleanliness","communication","accuracy"].map(name=>({name,label:name[0].toUpperCase()+name.slice(1),type:"number",min:1,max:5,value:5})),{name:"body",label:"Your experience",type:"textarea"}]} /></Panel><ReviewWorkspace userId={user.id}/></Workspace>;
 if (view === "support") {
  const contacts = (await prisma.siteSetting.findUnique({where:{key:"collaboration.contacts"}}))?.value as {roadside?:string;insurance?:string}|null;
  const privacyRequests=await prisma.privacyDeletion.findMany({where:{userId:user.id},orderBy:{createdAt:"desc"},take:5});
  const faq = await prisma.faq.findMany({ where: { isPublished: true, ...(q ? { OR: [{ question: { contains: q, mode: "insensitive" } }, { answer: { contains: q, mode: "insensitive" } }] } : {}) }, take: 30, orderBy: { position: "asc" } });
  return <Workspace eyebrow="Here to help" title="Support & roadside" description="For an immediate danger, serious injury, or emergency, call 911. Rent A 4Wheel is not an emergency responder or an insurer."><Panel title="Find an answer"><form className="flex gap-2"><input type="hidden" name="view" value="support"/><input className="workspace-input min-w-0 flex-1" aria-label="Search help" name="q" defaultValue={q}/><button className="min-h-11 shrink-0 whitespace-nowrap rounded-md bg-gold px-4 font-semibold text-black">Search</button></form>{faq.map(f=><details className="border-b border-white/10 py-4" key={f.id}><summary className="cursor-pointer">{f.question}</summary><p className="mt-3 whitespace-pre-wrap text-silver">{f.answer}</p></details>)}</Panel><Panel title="Roadside contacts"><p className="whitespace-pre-wrap text-silver">{contacts?.roadside ?? "Roadside contact not yet configured. For immediate danger, call 911."}</p><p className="mt-3 whitespace-pre-wrap text-silver">{contacts?.insurance ?? "Insurance contact not yet configured. Consult your signed agreement and insurance provider."}</p></Panel><Panel title="Open a ticket or report an incident"><CaseForm reservationId={reservationId} /></Panel><Panel title="Privacy request"><p className="mb-4 text-silver">Request a review of your data for deletion. Legal, security, financial, and agreement retention requirements may prevent immediate deletion.</p><ActionForm endpoint={endpoint} action="privacy" label="Request privacy review" />{privacyRequests.map(r=><p key={r.id} className="mt-3 text-sm text-silver">{r.createdAt.toLocaleDateString("en-US")} · {r.state.replaceAll("_"," ")}</p>)}</Panel></Workspace>;
 }
 if (view === "cases" || view === "operations") {
  const operating = view === "operations";
  if (operating && !["SUPPORT_AGENT","CLAIMS_AGENT","ADMIN","SUPER_ADMIN"].includes(actor.role)) return <Workspace eyebrow="Restricted workspace" title="Operations access required"><p>Contact your administrator about your assigned role.</p></Workspace>;
  const candidates = await prisma.serviceCase.findMany({ where: { AND: [scopes.caseWhere, q ? { OR: [{ title: { contains: q, mode:"insensitive" } }, { id:q }] } : {}] }, orderBy: { updatedAt: "desc" }, take: 30, skip: (page - 1) * 30 });
  const visible = [];
  for (const c of candidates) { try { const access = await caseAccess(prisma,user.id,c.id); if (!operating || access.role === "OPERATOR") visible.push(c); } catch {} }

  return <Workspace eyebrow={operating ? "Operator workspace" : "Your requests"} title={operating ? "Cases & operations" : "Claims, disputes & support"} description="Case decisions do not authorize charges or release deposits. Financial settlement uses its separate approved workflow."><Panel title="Case queue"><form className="mb-5 flex gap-2"><input type="hidden" name="view" value={view}/><input name="q" defaultValue={q} aria-label="Search case title or ID" className="workspace-input min-w-0 flex-1"/><button className="min-h-11 shrink-0 whitespace-nowrap rounded-md bg-gold px-4 font-semibold text-black">Search</button></form>{visible.length ? visible.map(c=><Link className="block border-b border-white/10 py-4" href={`/connect/cases/${c.id}`} key={c.id}><span className="text-xs uppercase text-gold">{c.kind} · {c.state.replaceAll("_"," ")}</span><span className="mt-1 block font-semibold">{c.title}</span><span className="text-xs text-silver">Response due {c.dueAt.toLocaleString("en-US")}</span></Link>) : <p className="text-silver">No cases in your queue.</p>}<Pager page={page} view={view} q={q} more={candidates.length===30}/></Panel>{operating && <><CommunitySla role={actor.role}/><CommunityAdminPanels role={actor.role} /></>}{!operating && <Panel title="Open a case"><CaseForm reservationId={reservationId} /></Panel>}</Workspace>;
 }
 const candidates = await prisma.conversation.findMany({ where: { AND: [scopes.conversationWhere, q ? { messages: { some: { OR: [{ body: { contains: q, mode: "insensitive" } }, ...(isOperator(actor.role,"MESSAGE") ? [{ revisions: { some: { body: { contains:q,mode:"insensitive" as const } } } }] : [])] } } } : {}] }, orderBy: { updatedAt: "desc" }, take: 30, skip: (page - 1) * 30 });
 const visible = [];
 for (const c of candidates) { try { await conversationAccess(prisma,user.id,c.id); const read = await prisma.conversationRead.findUnique({ where: { conversationId_userId: { conversationId:c.id,userId:user.id } } });const unread = await prisma.conversationMessage.count({ where: {conversationId:c.id,senderId:{not:user.id},createdAt:{gt:read?.readAt ?? new Date(0)}} });visible.push({...c,unread}); } catch {} }
 return <Workspace eyebrow="Stay connected" title="Your inbox" description="Private conversations with your trip participants. Never send identity documents, card details, or sensitive personal information in chat."><Panel title="Conversations"><form className="mb-4 flex gap-2"><input className="workspace-input min-w-0 flex-1" name="q" defaultValue={q} aria-label="Search messages"/><button className="min-h-11 shrink-0 whitespace-nowrap rounded-md bg-gold px-4 font-semibold text-black">Search</button></form>{visible.length ? visible.map(c=><Link key={c.id} href={`/connect/conversations/${c.id}`} className="flex items-center justify-between gap-4 border-b border-white/10 py-4"><span>{c.reservationId ? "Reservation conversation" : "Pre-booking inquiry"}<span className="block text-xs text-silver">{c.updatedAt.toLocaleString("en-US")}</span></span>{c.unread > 0 && <span className="rounded-full bg-gold px-3 py-1 text-black">{c.unread} unread</span>}</Link>) : <p className="text-silver">Your conversations will appear here.</p>}<Pager page={page} view={view} q={q} more={candidates.length===30}/></Panel><Panel title="Message about a reservation"><ActionForm endpoint={endpoint} action="conversation" fields={[{name:"reservationId",label:"Reservation ID"}]} label="Open conversation" redirectTo="/connect/conversations/:id" /></Panel><Panel title="Ask before booking"><ActionForm endpoint={endpoint} action="conversation" fields={[{name:"vehicleId",label:"Vehicle ID"}]} label="Start inquiry" redirectTo="/connect/conversations/:id" /></Panel></Workspace>;
}
function CaseForm({reservationId}:{reservationId:string}) { return <CaseIntake reservationId={reservationId}/>; }

function Pager({page,view,q,more}:{page:number;view:string;q:string;more:boolean}){return <nav aria-label="Results pages" className="mt-4 flex gap-4 text-gold">{page>1 && <Link href={`?view=${view}&q=${encodeURIComponent(q)}&page=${page-1}`}>Previous page</Link>}{more && <Link href={`?view=${view}&q=${encodeURIComponent(q)}&page=${page+1}`}>Next page</Link>}</nav>;}
