import { CommunityAdminPanels } from "@/components/marketplace/community-admin-panels";
import Link from "next/link";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Workspace, Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
import { conversationAccess } from "@/lib/conversations";
import { caseAccess } from "@/lib/service-cases";
import { isOperator } from "@/lib/collaboration-access";
const endpoint = "/api/community";
export default async function Page({ searchParams }: { searchParams: Promise<{ view?: string; q?: string; reservationId?: string }> }) {
 const user = (await auth())!.user!, { view = "inbox", q = "", reservationId = "" } = await searchParams;
 const actor = await prisma.user.findUniqueOrThrow({ where: { id: user.id } });
 if (view === "notifications") {
  const notices = await prisma.inboxNotice.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" }, take: 100 });
  return <Workspace eyebrow="Your account" title="Notification center" description="Important account and legal updates stay available here, regardless of email delivery."><Panel title="Updates">{notices.length ? notices.map(n=><Link className="block border-b border-white/10 py-4" href={`/api/community/notices/${n.id}`} key={n.id}>{!n.readAt && <span className="text-gold">● </span>}{n.title}<span className="block text-xs text-silver">{n.createdAt.toLocaleString("en-US")}</span></Link>) : <p className="text-silver">No updates yet.</p>}</Panel><Panel title="Email preferences"><ActionForm endpoint={endpoint} action="preference" fields={[{name:"category",label:"Category",options:["MESSAGE","CLAIM","DISPUTE","INCIDENT","TICKET","REVIEW","BOOKING","PAYMENT"]},{name:"email",label:"Optional email delivery",options:["on","off"]},{name:"sms",label:"SMS (requires handset consent)",options:["off","on"]}]} /><p className="mt-4 text-sm text-silver">Required transactional and legal notifications cannot be disabled.</p></Panel><Panel title="Text-message consent"><p className="mb-4 text-silver">Optional account texts. Message and data rates may apply. Reply STOP to opt out. After requesting enrollment, send START from that phone to {process.env.TWILIO_FROM_NUMBER ?? "the business number (not yet configured)"} within 24 hours. No texts are sent until that handset confirms.</p><ActionForm endpoint={endpoint} action="smsConsent" fields={[{name:"phone",label:"International phone number (+ country code)"},{name:"consent",label:"I consent to account update texts",options:["no","yes"]}]} label="Request text enrollment" /></Panel></Workspace>;
 }
 if (view === "reviews") return <Workspace eyebrow="After your trip" title="Share your experience" description="Reviews stay blind for the configured review period. Customer reputation is private to authorized hosts."><Panel title="Write a review"><ActionForm endpoint={endpoint} action="review" fields={[{name:"reservationId",label:"Reservation ID",value:reservationId},{name:"subject",label:"Review subject",options:["VEHICLE","HOST","CUSTOMER"]},... ["rating","cleanliness","communication","accuracy"].map(name=>({name,label:name[0].toUpperCase()+name.slice(1),type:"number",min:1,max:5,value:5})),{name:"body",label:"Your experience",type:"textarea"}]} /></Panel></Workspace>;
 if (view === "support") {
  const contacts = (await prisma.siteSetting.findUnique({where:{key:"collaboration.contacts"}}))?.value as {roadside?:string;insurance?:string}|null;
  const faq = await prisma.faq.findMany({ where: { isPublished: true, ...(q ? { OR: [{ question: { contains: q, mode: "insensitive" } }, { answer: { contains: q, mode: "insensitive" } }] } : {}) }, take: 30, orderBy: { position: "asc" } });
  return <Workspace eyebrow="Here to help" title="Support & roadside" description="For an immediate danger, serious injury, or emergency, call 911. Rent A 4Wheel is not an emergency responder or an insurer."><Panel title="Find an answer"><form className="flex gap-2"><input type="hidden" name="view" value="support"/><input className="workspace-input min-w-0" aria-label="Search help" name="q" defaultValue={q}/><button className="rounded bg-gold px-4 text-black">Search</button></form>{faq.map(f=><details className="border-b border-white/10 py-4" key={f.id}><summary className="cursor-pointer">{f.question}</summary><p className="mt-3 whitespace-pre-wrap text-silver">{f.answer}</p></details>)}</Panel><Panel title="Roadside contacts"><p className="whitespace-pre-wrap text-silver">{contacts?.roadside ?? "Roadside contact not yet configured. For immediate danger, call 911."}</p><p className="mt-3 whitespace-pre-wrap text-silver">{contacts?.insurance ?? "Insurance contact not yet configured. Consult your signed agreement and insurance provider."}</p></Panel><Panel title="Open a ticket or report an incident"><CaseForm reservationId={reservationId} /></Panel><Panel title="Privacy request"><p className="mb-4 text-silver">Request a review of your data for deletion. Legal, security, financial, and agreement retention requirements may prevent immediate deletion.</p><ActionForm endpoint={endpoint} action="privacy" label="Request privacy review" /></Panel></Workspace>;
 }
 if (view === "cases" || view === "operations") {
  const operating = view === "operations";
  if (operating && !["SUPPORT_AGENT","CLAIMS_AGENT","ADMIN","SUPER_ADMIN"].includes(actor.role)) return <Workspace eyebrow="Restricted workspace" title="Operations access required"><p>Contact your administrator about your assigned role.</p></Workspace>;
  const candidates = await prisma.serviceCase.findMany({ where: q ? { OR: [{ title: { contains: q, mode:"insensitive" } }, { id:q }] } : {}, orderBy: { updatedAt: "desc" }, take: 200 });
  const visible = [];
  for (const c of candidates) { try { const access = await caseAccess(prisma,user.id,c.id); if (!operating || access.role === "OPERATOR") visible.push(c); } catch {} }
  const failed = operating && isOperator(actor.role,"MESSAGE") ? await prisma.outboxMessage.count({where:{status:"FAILED"}}) : 0;
  return <Workspace eyebrow={operating ? "Operator workspace" : "Your requests"} title={operating ? "Cases & operations" : "Claims, disputes & support"} description="Case decisions do not authorize charges or release deposits. Financial settlement uses its separate approved workflow."><Panel title="Case queue"><form className="mb-5 flex gap-2"><input type="hidden" name="view" value={view}/><input name="q" defaultValue={q} aria-label="Search case title or ID" className="workspace-input min-w-0"/><button className="rounded bg-gold px-4 text-black">Search</button></form>{operating && <p className="mb-3 text-silver">{visible.filter(c=>c.dueAt < new Date() && c.state !== "CLOSED").length} overdue responses · {visible.filter(c=>c.safetyBlock).length} safety blocks · {failed} failed email deliveries</p>}{visible.length ? visible.map(c=><Link className="block border-b border-white/10 py-4" href={`/connect/cases/${c.id}`} key={c.id}><span className="text-xs uppercase text-gold">{c.kind} · {c.state.replaceAll("_"," ")}</span><span className="mt-1 block font-semibold">{c.title}</span><span className="text-xs text-silver">Response due {c.dueAt.toLocaleString("en-US")}</span></Link>) : <p className="text-silver">No cases in your queue.</p>}</Panel>{operating && <CommunityAdminPanels role={actor.role} />}{!operating && <Panel title="Open a case"><CaseForm reservationId={reservationId} /></Panel>}</Workspace>;
 }
 const candidates = await prisma.conversation.findMany({ orderBy: { updatedAt: "desc" }, take: 200 });
 const visible = [];
 for (const c of candidates) { try { await conversationAccess(prisma,user.id,c.id); const read = await prisma.conversationRead.findUnique({ where: { conversationId_userId: { conversationId:c.id,userId:user.id } } });const unread = await prisma.conversationMessage.count({ where: {conversationId:c.id,senderId:{not:user.id},createdAt:{gt:read?.readAt ?? new Date(0)}} });visible.push({...c,unread}); } catch {} }
 return <Workspace eyebrow="Stay connected" title="Your inbox" description="Private conversations with your trip participants. Never send identity documents, card details, or sensitive personal information in chat."><Panel title="Conversations">{visible.length ? visible.map(c=><Link key={c.id} href={`/connect/conversations/${c.id}`} className="flex items-center justify-between gap-4 border-b border-white/10 py-4"><span>{c.reservationId ? "Reservation conversation" : "Pre-booking inquiry"}<span className="block text-xs text-silver">{c.updatedAt.toLocaleString("en-US")}</span></span>{c.unread > 0 && <span className="rounded-full bg-gold px-3 py-1 text-black">{c.unread} unread</span>}</Link>) : <p className="text-silver">Your conversations will appear here.</p>}</Panel><Panel title="Message about a reservation"><ActionForm endpoint={endpoint} action="conversation" fields={[{name:"reservationId",label:"Reservation ID"}]} label="Open conversation" redirectTo="/connect/conversations/:id" /></Panel><Panel title="Ask before booking"><ActionForm endpoint={endpoint} action="conversation" fields={[{name:"vehicleId",label:"Vehicle ID"}]} label="Start inquiry" redirectTo="/connect/conversations/:id" /></Panel></Workspace>;
}
function CaseForm({ reservationId }: { reservationId: string }) { return <ActionForm endpoint={endpoint} action="case" redirectTo="/connect/cases/:id" label="Open request" fields={[{name:"kind",label:"Request type",options:["TICKET","CLAIM","DISPUTE","INCIDENT"]},{name:"reservationId",label:"Reservation ID (required except general support)",required:false,value:reservationId},{name:"category",label:"Category",options:["GENERAL","DAMAGE","MILEAGE","FUEL","LATE_RETURN","CLEANING","CANCELLATION","REFUND","UNAUTHORIZED_USE","OTHER_CHARGES","ACCIDENT","BREAKDOWN","FLAT_TIRE","LOST_KEY","TOWING","UNSAFE_VEHICLE","POLICE_REPORT","INJURY","THEFT"]},{name:"title",label:"Short summary"},{name:"body",label:"What happened?",type:"textarea"},{name:"location",label:"Location / damaged area",required:false},{name:"severity",label:"Severity",options:["MINOR","MODERATE","SEVERE"]},{name:"people",label:"People involved (only necessary details)",required:false},{name:"policeReport",label:"Police report number",required:false},{name:"provider",label:"Tow or repair contact",required:false},{name:"linkedCaseId",label:"Related case ID (if any)",required:false}]} />; }
