import React, { useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { Routes } from '../navigation';
import { session, mutate, friendly } from '../runtime';
import { Page, Card, Copy, Hint, Button, Field, ErrorText, Busy } from '../ui';
import { useAction } from '../hooks';
import { PendingReply } from '../pending-reply';
export function Inbox({ navigation }: NativeStackScreenProps<Routes, 'Inbox'>) {
  const [cursor, setCursor] = useState<string | undefined>();
  const q = useQuery({ queryKey: ['conversations', cursor], queryFn: ({ signal }) => session.call('conversations', { query: { cursor } }, signal) });
  return <Page title="Messages"><Hint>Open a conversation from your reservation to contact its host. Never send license or payment details in chat.</Hint><Button title="Refresh conversations" onPress={() => { setCursor(undefined); void q.refetch(); }} />{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No conversations yet.</Hint>}{q.data.items.map(c => <Card key={c.id}><Hint>Updated {new Date(c.updatedAt).toLocaleString()}</Hint><Button title="Open reservation conversation" onPress={() => navigation.navigate('Messages', { id: c.id })} /></Card>)}{q.data.nextCursor && <Button title="More conversations" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}</Page>;
}
export function Messages({ route }: NativeStackScreenProps<Routes, 'Messages'>) {
  const { id } = route.params, [body, setBody] = useState(''), [cursor, setCursor] = useState<string | undefined>(), action = useAction();
  const q = useQuery({ queryKey: ['messages', id, cursor], queryFn: ({ signal }) => session.call('messages', { params: { id }, query: { cursor } }, signal), refetchInterval: 15000 });
  return <Page title="Trip conversation"><Hint>Messages are private to current trip participants. Contact local emergency services if anyone is in immediate danger.</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No messages yet.</Hint>}{q.data.items.map(m => <Card key={m.id}><Copy>{m.body}</Copy><Hint>{new Date(m.createdAt).toLocaleString()}</Hint></Card>)}{q.data.nextCursor && <Button title="Next messages" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}
    <Field label="Message" value={body} onChangeText={setBody} multiline maxLength={5000} /><ErrorText message={action.error} /><Button title="Send message" disabled={action.busy || !body.trim()} onPress={() => void action.run(async () => { await mutate('sendMessage', { params: { id }, body: { body } }); setBody(''); await q.refetch(); })} /><Button title="Refresh messages" onPress={() => { void q.refetch(); }} /></Page>;
}
export function Notices() {
  const [cursor, setCursor] = useState<string | undefined>();
  const q = useQuery({ queryKey: ['notices', cursor], queryFn: ({ signal }) => session.call('notifications', { query: { cursor } }, signal) });
  return <Page title="Notices"><Button title="Refresh notices" onPress={() => { setCursor(undefined); void q.refetch(); }} />{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>You’re all caught up.</Hint>}{q.data.items.map(n => <Card key={n.id}><Copy>{n.title}</Copy><Hint>{n.category} · {new Date(n.createdAt).toLocaleString()}</Hint></Card>)}{q.data.nextCursor && <Button title="More notices" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}</Page>;
}
export function Cases({ navigation, route }: NativeStackScreenProps<Routes, 'Cases'>) {
  const [cursor, setCursor] = useState<string | undefined>(), [title, setTitle] = useState(''), [body, setBody] = useState(''), action = useAction();
  const q = useQuery({ queryKey: ['cases', cursor], queryFn: ({ signal }) => session.call('cases', { query: { cursor } }, signal) });
  return <Page title="Support & cases"><Hint>{route.params?.reservationId ? 'Your new request will be linked to this reservation.' : 'Create a standalone support request, or open help from a reservation to link it.'}</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No cases currently visible.</Hint>}{q.data.items.map(c => <Card key={c.id}><Copy>{c.title}</Copy><Hint>{c.kind} · {c.state}</Hint><Button title="View case" onPress={() => navigation.navigate('Case', { id: c.id })} /></Card>)}{q.data.nextCursor && <Button title="More cases" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}
    <Field label="Request title" value={title} onChangeText={setTitle} maxLength={160} /><Field label="Describe what happened" value={body} onChangeText={setBody} multiline maxLength={5000} /><Hint>Do not include identity documents or payment credentials. Use the secure document flow for identity evidence.</Hint><ErrorText message={action.error} /><Button title="Open support request" disabled={action.busy || title.trim().length < 3 || body.trim().length < 10} onPress={() => void action.run(async () => { const c = await mutate('openCase', { body: { kind: 'TICKET', category: 'GENERAL', title, body, reservationId: route.params?.reservationId } }); setTitle(''); setBody(''); navigation.navigate('Case', { id: c.id }); })} /><Button title="Refresh cases" onPress={() => { void q.refetch(); }} /></Page>;
}
export function Case({ route }: NativeStackScreenProps<Routes, 'Case'>) {
  const pending = useRef(new PendingReply()), [replyPending, setReplyPending] = useState(false);
  const { id } = route.params, [body, setBody] = useState(''), [cursor, setCursor] = useState<string | undefined>(), action = useAction();
  const q = useQuery({ queryKey: ['case', id], queryFn: ({ signal }) => session.call('serviceCase', { params: { id } }, signal) });
  const events = useQuery({ queryKey: ['caseEvents', id, cursor], queryFn: ({ signal }) => session.call('caseEvents', { params: { id }, query: { cursor } }, signal) });
  return <Page title={q.data?.title ?? 'Support case'}>{q.isPending && <Busy />}{q.isError && <ErrorText message={friendly(q.error)} />}<Hint>{q.data?.state}</Hint>{events.isError && <ErrorText message={friendly(events.error)} />}{events.data?.items.map(e => <Card key={e.id}><Copy>{e.body}</Copy><Hint>{e.action} · {new Date(e.createdAt).toLocaleString()}</Hint></Card>)}{events.data?.nextCursor && <Button title="More case updates" onPress={() => setCursor(events.data?.nextCursor ?? undefined)} />}{q.isPending || events.isPending ? <Busy /> : <><Field label="Reply to case" editable={!replyPending} value={body} onChangeText={setBody} multiline maxLength={5000} /><ErrorText message={action.error} /><Button title="Send case reply" disabled={action.busy || !q.data || !body.trim()} onPress={() => void action.run(async () => { setReplyPending(true); await pending.current.send({ id, body, version: q.data!.version }, frozen => mutate('replyCase', { params: { id: frozen.id }, body: { body: frozen.body, version: frozen.version } })); setReplyPending(false); setBody(''); await Promise.all([q.refetch(), events.refetch()]); })} /></>}<Button title="Refresh case" onPress={() => { void q.refetch(); void events.refetch(); }} /></Page>;
}
export function Review({ route }: NativeStackScreenProps<Routes, 'Review'>) {
  const [body, setBody] = useState(''), [rating, setRating] = useState('5'), [cleanliness, setCleanliness] = useState('5'), [communication, setCommunication] = useState('5'), [accuracy, setAccuracy] = useState('5'), [saved, setSaved] = useState(false), action = useAction();
  return <Page title="How was your trip?"><Hint>Review eligibility and publication timing are decided by the server.</Hint>{([[rating, setRating, 'Overall rating'], [cleanliness, setCleanliness, 'Cleanliness'], [communication, setCommunication, 'Communication'], [accuracy, setAccuracy, 'Listing accuracy']] as const).map(([value, setter, label]) => <Field key={label} label={label + ' (1–5)'} value={value} onChangeText={setter} keyboardType="number-pad" maxLength={1} />)}<Field label="Your review" value={body} onChangeText={setBody} multiline maxLength={5000} /><ErrorText message={action.error} /><Button title="Submit vehicle review" disabled={action.busy || saved || body.trim().length < 3 || ![rating, cleanliness, communication, accuracy].every(v => /^[1-5]$/.test(v))} onPress={() => void action.run(async () => { await mutate('saveReview', { body: { reservationId: route.params.id, subject: 'VEHICLE', body, rating: Number(rating), cleanliness: Number(cleanliness), communication: Number(communication), accuracy: Number(accuracy) } }); setSaved(true); })} />{saved && <Copy>Review saved. Publication follows the server’s review policy.</Copy>}</Page>;
}
