import React, { useState } from 'react';
import { useCaptureProtection } from '../screen-privacy';
import { useQuery } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { Routes } from '../navigation';
import { session, mutate, friendly } from '../runtime';
import { Page, Card, Copy, Hint, Button, Field, ErrorText, Busy, money } from '../ui';
import { useAction } from '../hooks';
import { DateField } from './discovery';
import { PrivateEvidence } from '../private-evidence';

const contextQuery = () => session.call('hostContext', {});
export function HostWelcome({ navigation }: NativeStackScreenProps<Routes, 'Home'>) {
  return <Page title="Your hosting day, in hand."><Hint>Manage your vehicles, meet your guests and keep every handoff documented.</Hint><Card><Copy>For independent vehicle providers and their authorized team.</Copy><Hint>Sign in with the phone or verified email linked to your host account. Creating a customer account does not grant host access.</Hint></Card><Button title="Sign in to hosting" onPress={() => navigation.navigate('SignIn')} /><Hint>Host applications and employee invitations are currently managed on the website. No automatic account transfer or live finance is available.</Hint></Page>;
}
export function HostDashboard({ navigation }: NativeStackScreenProps<Routes, 'Home'>) {
  const q = useQuery({ queryKey: ['hostContext'], queryFn: contextQuery });
  return <Page title="Host dashboard">{q.isPending ? <Busy /> : q.isError ? <><ErrorText message={friendly(q.error)} /><Hint>Hosting requires a current owner or employee membership. Contact your business owner if access was removed.</Hint></> : <><Copy>{q.data.name} · {q.data.role}</Copy><Card><Copy>{q.data.fleetCount} vehicles · {q.data.upcomingCount} upcoming · {q.data.activeCount} active or returning</Copy><Hint>You store, maintain and hand over your vehicles. Rent A 4Wheel supplies marketplace, verification and support workflows.</Hint></Card><Button title="Fleet & calendar" onPress={() => navigation.navigate('HostFleet')} /><Button title="Reservations & handoffs" onPress={() => navigation.navigate('HostReservations')} /><Button title="Customer messages" onPress={() => navigation.navigate('Inbox')} /><Button title="Notices" onPress={() => navigation.navigate('Notices')} /><Button title="Support & cases" onPress={() => navigation.navigate('Cases')} />{q.data.canViewEarnings && <Button title="Owner earnings" onPress={() => navigation.navigate('HostEarnings')} />}{!q.data.canViewEarnings && <Hint>Owner financial statements are not available to employees.</Hint>}</>}<Button title="Refresh host access" onPress={() => void q.refetch()} /><Button title="Account & devices" onPress={() => navigation.navigate('Account')} /><Hint>Staging · Live payments and payouts are disabled.</Hint></Page>;
}
export function HostFleet({ navigation }: NativeStackScreenProps<Routes, 'HostFleet'>) {
  const [cursor, setCursor] = useState<string | undefined>();
  const q = useQuery({ queryKey: ['hostFleet', cursor], queryFn: ({ signal }) => session.call('hostFleet', { query: { cursor } }, signal) });
  return <Page title="Your fleet"><Hint>Listing creation, approval and legal ownership changes remain web-only. This app does not activate unapproved vehicles.</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No vehicles are assigned to this business.</Hint>}{q.data.items.map(v => <Card key={v.id}><Copy>{v.year} {v.make} {v.model}</Copy><Hint>{v.status} · {v.listingApproval} · {v.location}</Hint><Button title={`Manage ${v.make} ${v.model}`} onPress={() => navigation.navigate('HostVehicle', { id: v.id })} /></Card>)}{q.data.nextCursor && <Button title="More vehicles" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}<Button title="Refresh fleet" onPress={() => void q.refetch()} /></Page>;
}
function monthWindow(offset: number) { const now = new Date(); return { startAt: new Date(now.getFullYear(), now.getMonth() + offset, 1).toISOString(), endAt: new Date(now.getFullYear(), now.getMonth() + offset + 1, 1).toISOString() }; }
export function HostVehicle({ route, navigation }: NativeStackScreenProps<Routes, 'HostVehicle'>) {
  const { id } = route.params, action = useAction();
  const [offset, setOffset] = useState(0), [start, setStart] = useState(() => new Date(Date.now() + 86400000)), [end, setEnd] = useState(() => new Date(Date.now() + 172800000)), [notes, setNotes] = useState('');
  const [reason, setReason] = useState<'MAINTENANCE' | 'OWNER_REQUEST' | 'OTHER'>('MAINTENANCE');
  const q = useQuery({ queryKey: ['hostVehicle', id], queryFn: ({ signal }) => session.call('hostVehicle', { params: { id } }, signal) });
  const permissions = useQuery({ queryKey: ['hostContext'], queryFn: contextQuery });
  const window = monthWindow(offset);
  const calendar = useQuery({ queryKey: ['hostCalendar', id, window], queryFn: ({ signal }) => session.call('hostCalendar', { params: { id }, body: window }, signal) });
  const refresh = async () => { await Promise.all([q.refetch(), calendar.refetch(), permissions.refetch()]); };
  return <Page title={q.data ? `${q.data.make} ${q.data.model}` : 'Listing & calendar'}>{q.isPending && <Busy />}{q.isError && <ErrorText message={friendly(q.error)} />}{q.data && <Card>{q.data.isDemo && <Copy>Synthetic/demo inventory</Copy>}<Copy>{q.data.status} · {q.data.listingApproval}</Copy><Hint>{q.data.location} · {q.data.mileage} miles</Hint><Copy>{q.data.description}</Copy><Hint>{q.data.rules}</Hint><Copy>{q.data.isBookable ? 'Accepting bookings, subject to server gates' : 'Bookings paused'}</Copy></Card>}
    <Copy>{new Date(window.startAt).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</Copy><Hint>Calendar times use your device timezone. A block is saved only after the server checks bookings and live holds.</Hint><Button title="Previous month" onPress={() => setOffset(o => o - 1)} /><Button title="Next month" onPress={() => setOffset(o => o + 1)} />
    {calendar.isPending ? <Busy /> : calendar.isError ? <ErrorText message={friendly(calendar.error)} /> : <>{calendar.data.truncated && <ErrorText message="This month exceeds the display limit. Use the website for the complete calendar." />}{!calendar.data.blocks.length && !calendar.data.reservations.length && <Hint>No blocks or reservations in this month.</Hint>}{calendar.data.reservations.map(r => <Card key={r.id}><Copy>{r.confirmationNumber} · {r.status}</Copy><Hint>{new Date(r.pickupAt).toLocaleString()} – {new Date(r.returnAt).toLocaleString()}</Hint><Button title={`Open ${r.confirmationNumber}`} onPress={() => navigation.navigate('HostTrip', { id: r.id })} /></Card>)}{calendar.data.blocks.map(b => <Card key={b.id}><Copy>{b.reason}</Copy><Hint>{new Date(b.startAt).toLocaleString()} – {new Date(b.endAt).toLocaleString()}</Hint><Hint>{b.notes}</Hint>{permissions.data?.canManageFleet && <Button title="Remove calendar block" disabled={action.busy} onPress={() => void action.run(async () => { await mutate('hostAvailability', { params: { id }, body: { action: 'unblock', id: b.id } }); await refresh(); })} />}</Card>)}</>}
    {permissions.data?.canManageFleet ? <><DateField title="Block starts" value={start} onChange={setStart} /><DateField title="Block ends" value={end} onChange={setEnd} />{(['MAINTENANCE', 'OWNER_REQUEST', 'OTHER'] as const).map(r => <Button key={r} title={`${reason === r ? 'Selected: ' : ''}${r.replaceAll('_', ' ')}`} onPress={() => setReason(r)} />)}<Field label="Calendar block notes" value={notes} onChangeText={setNotes} maxLength={2000} /><Button title="Save calendar block" disabled={action.busy || end <= start} onPress={() => void action.run(async () => { await mutate('hostAvailability', { params: { id }, body: { action: 'block', startAt: start.toISOString(), endAt: end.toISOString(), reason, notes } }); await refresh(); })} /><Button title={q.data?.isBookable ? 'Pause new bookings' : 'Request accepting bookings'} disabled={action.busy || !q.data} onPress={() => void action.run(async () => { await mutate('hostAvailability', { params: { id }, body: { action: 'availability', isBookable: !q.data!.isBookable } }); await refresh(); })} /></> : <Hint>Calendar changes require owner or manager access.</Hint>}<ErrorText message={action.error} /><Button title="Refresh listing & calendar" onPress={() => void refresh()} /></Page>;
}
export function HostReservations({ navigation }: NativeStackScreenProps<Routes, 'HostReservations'>) {
  const [cursor, setCursor] = useState<string | undefined>();
  const q = useQuery({ queryKey: ['hostReservations', cursor], queryFn: ({ signal }) => session.call('hostReservations', { query: { cursor } }, signal) });
  return <Page title="Reservations & handoffs"><Hint>Review status and pickup times before meeting the guest. List times use your device timezone. Only the customer can start their trip.</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No reservations are currently assigned.</Hint>}{q.data.items.map(r => <Card key={r.id}><Copy>{r.confirmationNumber} · {r.status}</Copy><Hint>{new Date(r.pickupAt).toLocaleString()} – {new Date(r.returnAt).toLocaleString()}</Hint><Button title={`Open ${r.confirmationNumber}`} onPress={() => navigation.navigate('HostTrip', { id: r.id })} /></Card>)}{q.data.nextCursor && <Button title="More reservations" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}<Button title="Refresh reservations" onPress={() => void q.refetch()} /></Page>;
}
export function HostTrip({ route, navigation }: NativeStackScreenProps<Routes, 'HostTrip'>) {
  const { id } = route.params, action = useAction();
  const r = useQuery({ queryKey: ['reservation', id], queryFn: ({ signal }) => session.call('reservation', { params: { id } }, signal) });
  const q = useQuery({ queryKey: ['hostTrip', id], queryFn: ({ signal }) => session.call('hostTrip', { params: { id } }, signal) });
  const refresh = async () => { await Promise.all([r.refetch(), q.refetch()]); };
  return <Page title={r.data?.confirmationNumber ?? 'Host trip'}>{r.isPending || q.isPending ? <Busy /> : r.isError || q.isError ? <ErrorText message={friendly(r.error ?? q.error)} /> : <><Copy>{r.data.status} · Guest: {q.data.customerName}</Copy><Card><Copy>Pickup instructions</Copy><Hint>{r.data.pickupLocation}</Hint><Hint>{new Date(r.data.pickupAt).toLocaleString(undefined, { timeZone: r.data.bookingTimezone })} · Booking timezone {r.data.bookingTimezone}</Hint><Hint>Coordinate physical pickup and return in the private reservation conversation.</Hint></Card><Button title="Message customer" disabled={action.busy} onPress={() => void action.run(async () => { const c = await mutate('openConversation', { body: { reservationId: id } }); navigation.navigate('Messages', { id: c.id }); })} /><Card><Copy>{q.data.handoffVerified ? 'Identity handoff recorded' : 'Identity comparison required'}</Copy><Button title="Compare identity in person" onPress={() => navigation.navigate('HostIdentity', { id })} /><Button title="Host photos & condition reports" onPress={() => navigation.navigate('Inspection', { id, host: true })} /><Copy>{q.data.keysReleased ? 'Keys handoff recorded' : 'Keys not handed over'}</Copy>{q.data.keyReleaseGate.reasons.map(reason => <Hint key={reason}>{reason}</Hint>)}<Button title="Record keys handed to customer" disabled={action.busy || q.data.keysReleased || !q.data.keyReleaseGate.canStart} onPress={() => void action.run(async () => { await mutate('tripKeys', { params: { id }, body: {} }); await refresh(); })} /><Hint>The guest must complete their own documents, agreement, report and trip-start action. This button cannot start a trip.</Hint></Card>{r.data.status === 'ACTIVE' && <Button title="Begin return inspection" disabled={action.busy} onPress={() => void action.run(async () => { await mutate('tripReturn', { params: { id }, body: {} }); await refresh(); })} />}{r.data.status === 'RETURN_IN_PROGRESS' && <><Hint>Both authors must accept their return reports. Claims and financial review can block completion. Deposit decisions belong to server-side financial recovery.</Hint><Button title="Complete return after both reports" disabled={action.busy} onPress={() => void action.run(async () => { await mutate('tripComplete', { params: { id }, body: {} }); await refresh(); })} /></>}<Button title="Report damage or incident" onPress={() => navigation.navigate('HostIncident', { id })} /><Button title="Reservation support" onPress={() => navigation.navigate('Cases', { reservationId: id })} /></>}<ErrorText message={action.error} /><Button title="Refresh handoff & trip gates" onPress={() => void refresh()} /></Page>;
}
export function HostIdentity({ route }: NativeStackScreenProps<Routes, 'HostIdentity'>) {
  const captureReady = useCaptureProtection();
  const { id } = route.params, action = useAction();
  const [license, setLicense] = useState(false), [unexpired, setUnexpired] = useState(false), [selfie, setSelfie] = useState(false), [saved, setSaved] = useState(false);
  const q = useQuery({ queryKey: ['identityDocuments', id], queryFn: ({ signal }) => session.call('reservationDocuments', { params: { id } }, signal) });
  if (!captureReady) return <Page title="Private comparison"><Hint>Preparing screen protection. Restart the app if this persists.</Hint></Page>;
  return <Page title="In-person identity comparison"><Hint>Meet the guest in person. Compare their physical license with the submitted front/back and compare their face with the submitted selfie. Do not save, share or photograph identity evidence. Record only what you actually verified.</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : q.data.items.map(d => <Card key={d.id}><Copy>{d.type.replaceAll('_', ' ')}</Copy><Hint>{d.status} · Scan: {d.malwareScanStatus}</Hint>{d.malwareScanStatus === 'CLEAN' ? <PrivateEvidence documentId={d.id} label={d.type} /> : <Hint>Quarantined evidence cannot be previewed. Ask the guest to resolve verification.</Hint>}</Card>)}<Button title={`${license ? 'Checked' : 'Unchecked'}: physical license matches upload`} onPress={() => { setLicense(!license); setSaved(false); }} /><Button title={`${unexpired ? 'Checked' : 'Unchecked'}: physical license is unexpired`} onPress={() => { setUnexpired(!unexpired); setSaved(false); }} /><Button title={`${selfie ? 'Checked' : 'Unchecked'}: guest matches selfie`} onPress={() => { setSelfie(!selfie); setSaved(false); }} /><Button title="Record identity comparison" disabled={action.busy || q.isError || q.isPending} onPress={() => void action.run(async () => { const result = await mutate('hostHandoff', { params: { id }, body: { licenseMatchesUpload: license, physicalLicenseUnexpired: unexpired, selfieMatchesCustomer: selfie } }); setSaved(result.verified); })} />{saved && <Copy>Comparison recorded. Other trip gates still apply.</Copy>}<ErrorText message={action.error} /></Page>;
}
export function HostEarnings() {
  const [cursor, setCursor] = useState<string | undefined>();
  const q = useQuery({ queryKey: ['hostEarnings', cursor], queryFn: ({ signal }) => session.call('hostEarnings', { query: { cursor } }, signal) });
  return <Page title="Owner earnings"><Hint>Owner-only statements. Sample/unapproved pricing; live payouts remain disabled. Taxes, deposits and unsettled funds are not platform revenue.</Hint>{q.isPending ? <Busy /> : q.isError ? <ErrorText message={friendly(q.error)} /> : <>{!q.data.items.length && <Hint>No accounted earnings yet.</Hint>}{q.data.items.map(e => <Card key={e.id}><Copy>{e.currency.toUpperCase()} · {e.held ? 'Held for review' : 'Recorded earnings'}</Copy><Hint>Gross {money(e.grossCents)} · Commission {money(e.commissionCents)}</Hint><Hint>Host discount {money(e.hostDiscountCents)} · Refunds {money(e.refundedCents)}</Hint><Hint>Adjustments {money(e.adjustmentCents)}</Hint><Copy>Net {money(e.netCents)}</Copy></Card>)}{q.data.nextCursor && <Button title="More earnings" onPress={() => setCursor(q.data.nextCursor ?? undefined)} />}</>}</Page>;
}
export function HostIncident({ route, navigation }: NativeStackScreenProps<Routes, 'HostIncident'>) {
  const { id } = route.params, action = useAction();
  const [kind, setKind] = useState<'CLAIM' | 'INCIDENT'>('CLAIM'), [title, setTitle] = useState(''), [body, setBody] = useState(''), [severity, setSeverity] = useState<'MINOR' | 'MODERATE' | 'SEVERE'>('MINOR');
  const [category, setCategory] = useState('ACCIDENT'), [selected, setSelected] = useState<string[]>([]);
  const q = useQuery({ queryKey: ['reports', id], queryFn: ({ signal }) => session.call('reports', { params: { id } }, signal) });
  return <Page title="Damage & incident intake"><Hint>For immediate danger, contact emergency services first. This records an operational case; it cannot charge the guest or release financial holds.</Hint><Button title={kind === 'CLAIM' ? 'Damage claim selected — switch to incident' : 'Incident selected — switch to damage claim'} onPress={() => setKind(k => k === 'CLAIM' ? 'INCIDENT' : 'CLAIM')} />{kind === 'INCIDENT' && <>{['ACCIDENT', 'BREAKDOWN', 'LOST_KEY', 'UNSAFE_VEHICLE', 'INJURY', 'THEFT'].map(c => <Button key={c} title={`${category === c ? 'Selected: ' : ''}${c}`} onPress={() => setCategory(c)} />)}{(['MINOR', 'MODERATE', 'SEVERE'] as const).map(s => <Button key={s} title={`${severity === s ? 'Selected: ' : ''}${s}`} onPress={() => setSeverity(s)} />)}</>}<Field label="Incident title" value={title} onChangeText={setTitle} maxLength={160} /><Field label="Incident description" value={body} onChangeText={setBody} multiline maxLength={5000} /><Hint>Select original photos from accepted condition reports. Identity documents are never case attachments.</Hint>{q.isError && <ErrorText message={friendly(q.error)} />}{q.data?.items.filter(r => r.acceptedAt).flatMap(r => r.photos.map(p => <Button key={p.id} title={`${selected.includes(p.id) ? 'Selected' : 'Attach'}: ${r.phase} ${r.submittedByRole} ${p.category}`} onPress={() => setSelected(s => s.includes(p.id) ? s.filter(x => x !== p.id) : [...s, p.id])} />))}<Button title="Submit incident for review" disabled={action.busy || title.trim().length < 3 || body.trim().length < 10} onPress={() => void action.run(async () => { const result = await mutate('openCase', { body: { kind, reservationId: id, category: kind === 'CLAIM' ? 'DAMAGE' : category, title, body, severity, originalPhotoIds: selected } }); navigation.navigate('Case', { id: result.id }); })} /><ErrorText message={action.error} /><Hint>Claims require release approval and an actual trip. If unavailable, contact support; do not settle charges outside the approved workflow.</Hint></Page>;
}
