"use client";
import { useState } from "react";
import { useSession } from "next-auth/react";
type Device={id:string;device:string;current:boolean;lastSeenAt:string;expires:string};
export function SecurityPanel({initial}:{initial:Device[]}){
 const [devices,setDevices]=useState<Device[]>(initial),[message,setMessage]=useState(""),[code,setCode]=useState("");const {update}=useSession();
 async function rotate(){try{const prior=await update();if(typeof prior?.credentialVersion!=="number")throw new Error("Session unavailable");const result=await update({action:"rotate",code});if(!result?.user||result.credentialVersion!==prior.credentialVersion+1)throw new Error("Reauthentication refused");setCode("");setMessage("Session credential rotated.");}catch{setMessage("A fresh security code is required.");}}
 async function reload(){const response=await fetch("/api/account/security",{cache:"no-store"});if(response.ok)setDevices((await response.json()).sessions);else setMessage("Sign in again to manage your sessions.");}
 async function command(action:string,id?:string){const response=await fetch("/api/account/security",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id})});setMessage(response.ok?"Security action saved.":"Unable to complete security action.");await reload();}
 return <div className="space-y-6"><p>Sessions expire after 30 minutes of inactivity or seven days. Revoking a session blocks its next authenticated request.</p><ul className="space-y-4">{devices.map(d=><li key={d.id} className="rounded border p-4"><strong>{d.device}{d.current?" (this device)":""}</strong><p>Last active: {new Date(d.lastSeenAt).toLocaleString()}</p><button className="underline" onClick={()=>command("revoke",d.id)}>Revoke session</button></li>)}</ul><button className="underline" onClick={()=>command("revokeAll")}>Revoke all sessions</button><section className="space-y-3"><h2 className="text-xl font-semibold">Reauthenticate this device</h2><button className="underline" onClick={()=>command("stepUp")}>Email a security code</button><label className="block">One-use security code<input className="block rounded border p-2" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" maxLength={6}/></label><button className="underline" onClick={rotate}>Rotate session credential</button></section><p role="status">{message}</p></div>;
}
