import React, { useId } from 'react';
import { ActivityIndicator, InputAccessoryView, Keyboard, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
export const colors = { bg: '#050505', card: '#161616', text: '#FFFFFF', muted: '#B7BBC4', gold: '#D6B66A', border: '#44464D', error: '#F5A2AB' };
export const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.bg }, content: { padding: 20, gap: 18, paddingBottom: 48, width: '100%', maxWidth: 720, alignSelf: 'center' }, title: { color: colors.text, fontSize: 30, fontWeight: '700' }, text: { color: colors.text, fontSize: 16, lineHeight: 24 }, muted: { color: colors.muted, fontSize: 15, lineHeight: 23 }, card: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: 18, gap: 12 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, input: { color: colors.text, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 10, minHeight: 52, padding: 14, fontSize: 16 }, button: { minHeight: 52, justifyContent: 'center', alignItems: 'center', padding: 14, borderRadius: 12, backgroundColor: colors.gold }, buttonText: { color: '#080808', fontWeight: '700', fontSize: 16 }, error: { color: colors.error, fontSize: 16, lineHeight: 24 } });
export function Page({ title, titleTestID, children }: React.PropsWithChildren<{ title: string; titleTestID?: string }>) { const insets = useSafeAreaInsets(); return <ScrollView style={[styles.page, { marginBottom: insets.bottom, marginLeft: insets.left, marginRight: insets.right }]} contentContainerStyle={[styles.content, { paddingBottom: 24 }]} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" automaticallyAdjustKeyboardInsets><Text style={{ color: colors.gold, fontSize: 12, letterSpacing: 2 }}>RENT A 4WHEEL</Text><Text accessibilityRole="header" testID={titleTestID} style={styles.title}>{title}</Text>{children}</ScrollView>; }
export const Copy = ({ children }: React.PropsWithChildren) => <Text style={styles.text}>{children}</Text>;
export const Hint = ({ children }: React.PropsWithChildren) => <Text style={styles.muted}>{children}</Text>;
export const Card = ({ children }: React.PropsWithChildren) => <View style={styles.card}>{children}</View>;
export function Button({ title, onPress, disabled = false, testID }: { title: string; onPress: () => void; disabled?: boolean; testID?: string }) { return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={title} accessibilityState={{ disabled }} disabled={disabled} onPress={() => { Keyboard.dismiss(); onPress(); }} style={({ pressed }) => [styles.button, { opacity: disabled ? 0.5 : pressed ? 0.8 : 1 }]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { const accessoryId = useId(); return <View style={{ gap: 6 }}><Text style={styles.text}>{label}</Text><TextInput {...props} inputAccessoryViewID={Platform.OS === 'ios' ? accessoryId : undefined} testID={"input-" + label} accessibilityLabel={label} placeholderTextColor={colors.muted} style={styles.input} />{Platform.OS === 'ios' && <InputAccessoryView nativeID={accessoryId}><View style={{ backgroundColor: colors.card, padding: 8 }}><Button title="Done editing" onPress={() => Keyboard.dismiss()} /></View></InputAccessoryView>}</View>; }
export const Busy = () => <ActivityIndicator accessibilityLabel="Loading from server" color={colors.gold} size="large" />;
export const ErrorText = ({ message }: { message: string }) => message ? <Text accessibilityRole="alert" accessibilityLiveRegion="polite" style={styles.error}>{message}</Text> : null;
export function money(cents: number | null | undefined) { return cents == null ? 'Not available' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100); }
