import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { hostFinancePage } from "@/lib/finance-page-access";
import { money } from "@/lib/finance-access";
import { FinanceWorkspace,FinanceRestricted,FinanceEmpty,FinanceStatus } from "@/components/marketplace/finance-workspace";
import { Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
export default async function EarningsPage(){
 const context=await hostFinancePage();if(!context)return <FinanceRestricted/>;
 const hostId=context.host.id;
 const [earnings,batches]=await Promise.all([prisma.hostEarning.findMany({where:{hostId},orderBy:{createdAt:"desc"},take:100}),prisma.payoutBatch.findMany({where:{hostId},orderBy:{createdAt:"desc"},take:100})]);
 const items=await prisma.payoutItem.findMany({where:{earningId:{in:earnings.map(e=>e.id)},active:true}}),disputes=await prisma.providerDispute.findMany({where:{reservationId:{in:earnings.map(e=>e.reservationId)},active:true},select:{reservationId:true}});
 const currencies=[...new Set(earnings.map(e=>e.currency))];
 return <FinanceWorkspace title="Your earnings" description="Follow each rental from payment through return review and confirmed payout. Holds require an authorized review.">
  <div className="grid gap-4 sm:grid-cols-3">{currencies.length?currencies.flatMap(currency=>{const rows=earnings.filter(e=>e.currency===currency);return [["Net earnings",rows.reduce((s,e)=>s+e.netCents+e.adjustmentCents-e.refundedCents,0)],["Refunded host share",rows.reduce((s,e)=>s+e.refundedCents,0)],["Confirmed bank payouts",batches.filter(b=>b.currency===currency&&b.state==="PAID").reduce((s,b)=>s+b.paidCents,0)]].map(([label,value])=><Panel key={currency+label} title={String(label)}><p className="text-3xl text-gold-bright">{money(Number(value),currency)}</p><p className="mt-2 text-xs text-silver">Latest 100 records · {currency.toUpperCase()}</p></Panel>);}):<Panel title="Start earning"><p className="text-silver">Confirmed rental payments will appear here after accounting reconciliation.</p></Panel>}</div>
  <Panel title="Reservation earnings">{earnings.length?<div className="space-y-4">{earnings.map(e=>{const item=items.find(i=>i.earningId===e.id),batch=batches.find(b=>b.id===item?.batchId),state=disputes.some(d=>d.reservationId===e.reservationId)?"DISPUTED":batch?.state??(e.holdReason?"ON_HOLD":e.availableAt&&e.availableAt<=new Date()?"AWAITING_ELIGIBILITY_CHECK":"PENDING");return <article key={e.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><Link href={`/host/reservations/${e.reservationId}`} className="break-all text-sm text-white">Reservation {e.reservationId}</Link><FinanceStatus value={state}/></div><dl className="mt-4 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4">{[["Rental gross",e.grossCents],["Host discount",e.hostDiscountCents],["Commission",e.commissionCents],["Adjustments",e.adjustmentCents],["Refunded",e.refundedCents],["Net earnings",e.netCents-e.refundedCents+e.adjustmentCents]].map(([label,value])=><div key={label}><dt className="text-silver">{label}</dt><dd className="mt-1 text-white">{money(Number(value),e.currency)}</dd></div>)}</dl><p className="mt-4 text-sm text-silver">{e.holdReason|| (e.availableAt?`Earliest availability: ${e.availableAt.toLocaleDateString("en-US",{timeZone:"America/Chicago"})}. Final eligibility is checked under financial locks.`:"Pending completed trip and settlement delay.")}</p>{batch&&<Link href={`/finance/payouts/${batch.id}`} className="mt-3 inline-block text-sm text-gold-bright">View payout →</Link>}</article>;})}</div>:<FinanceEmpty>No earnings yet. Completed payment accounting creates an immutable allocation for each rental.</FinanceEmpty>}</Panel>
  <Panel title="Request a payout"><p className="mb-5 text-sm text-silver">Only eligible earnings are reserved. Claims, unresolved returns, account requirements and settlement delays continue to block payout.</p><ActionForm endpoint="/api/finance" action="batch" label="Check eligible balance"/></Panel>
  <Panel title="Recent payout batches">{batches.length?<div className="divide-y divide-white/10">{batches.map(b=><Link key={b.id} href={`/finance/payouts/${b.id}`} className="flex flex-wrap justify-between gap-3 py-4"><span className="text-white">{money(b.amountCents,b.currency)} <span className="text-sm text-silver">· {b.createdAt.toLocaleDateString()}</span></span><FinanceStatus value={b.state}/></Link>)}</div>:<FinanceEmpty>No payouts have been reserved.</FinanceEmpty>}</Panel>
 </FinanceWorkspace>;
}
