import { prisma } from "@/lib/prisma";
import { hostFinancePage } from "@/lib/finance-page-access";
import { FinanceWorkspace,FinanceRestricted,FinanceStatus } from "@/components/marketplace/finance-workspace";
import { Panel } from "@/components/marketplace/workspace";
import { ActionForm } from "@/components/marketplace/action-form";
import { ConnectOnboarding } from "@/components/marketplace/connect-onboarding";
export default async function OnboardingPage(){
 const context=await hostFinancePage(true);if(!context)return <FinanceRestricted/>;
 const [account,employees]=await Promise.all([prisma.connectAccount.findUnique({where:{hostId:context.host.id}}),context.owner?prisma.hostEmployee.findMany({where:{hostId:context.host.id,isActive:true},include:{user:{select:{name:true}}}}):Promise.resolve([])]);
 return <FinanceWorkspace title="Payout settings" description="Stripe securely collects identity, tax and bank information. Returning here does not mean verification is complete.">
  <div className="grid gap-6 lg:grid-cols-2"><Panel title="Connect your business"><FinanceStatus value={!account?.active&&account?"DEACTIVATED":account?.verificationStatus??"NOT_CONNECTED"}/><p className="my-5 text-silver">Complete the requirements in Stripe, then refresh your verified status. We do not collect bank details or full tax identifiers.</p><ConnectOnboarding/><div className="mt-5"><ActionForm endpoint="/api/finance" action="sync" label="Refresh Stripe status"/></div></Panel><Panel title="Verification checklist"><dl className="space-y-4 text-sm">{[["Business details",account?.detailsSubmitted?"Submitted":"Required"],["Payouts",account?.payoutsEnabled?"Enabled by Stripe":"Requires action"],["Tax information",account?.taxStatus??"MISSING"],["Last synchronized",account?.synchronizedAt?.toLocaleString()??"Not yet synchronized"]].map(([label,value])=><div key={label} className="flex flex-wrap justify-between gap-3 border-b border-white/10 pb-3"><dt className="text-silver">{label}</dt><dd className="text-white">{value}</dd></div>)}</dl><p className="mt-5 text-sm text-silver">Final 1099 eligibility and filing require tax-professional/provider confirmation. Open Stripe to view and supply outstanding requirements.</p></Panel></div>
  <Panel title="Payout schedule"><p className="mb-5 text-sm text-silver">Your selection must be permitted by an approved business policy. Small balances carry forward.</p><ActionForm endpoint="/api/finance" action="schedule" fields={[{name:"schedule",label:"Frequency",options:["MANUAL","WEEKLY","TWICE_MONTHLY","MONTHLY"],value:account?.schedule??"MANUAL"},{name:"timezone",label:"Time zone",value:account?.timezone??"America/Chicago"},{name:"minimumCents",label:"Minimum payout (USD)",type:"money",min:0.01,value:(account?.minimumCents??100)/100}]} label="Save payout schedule"/></Panel>
  {context.owner&&<Panel title="Employee finance permissions"><p className="mb-5 text-sm text-silver">Finance access is separate from operational access. Only managers may manage payout settings.</p>{employees.map(e=><div key={e.id} className="mb-6 rounded-xl border border-white/10 p-4"><p className="mb-4 text-white">{e.user.name||"Team member"} · {e.role}</p><div className="grid gap-5 sm:grid-cols-2"><ActionForm endpoint="/api/finance" action="grant" values={{employeeId:e.id}} fields={[{name:"manage",label:"Manage settings",options:e.role==="MANAGER"?["no","yes"]:["no"]}]} label="Grant finance access"/><ActionForm endpoint="/api/finance" action="revokeGrant" values={{employeeId:e.id}} label="Revoke finance access"/></div></div>)}</Panel>}
 </FinanceWorkspace>;
}
