import { prisma } from "@/lib/prisma";
import { adminFinancePage } from "@/lib/finance-page-access";
import { FinanceWorkspace,FinanceRestricted,FinanceStatus } from "@/components/marketplace/finance-workspace";
import { Panel } from "@/components/marketplace/workspace";
import { ActionForm,type WorkspaceField } from "@/components/marketplace/action-form";
export default async function RulesPage(){const actor=await adminFinancePage();if(!actor)return <FinanceRestricted/>;const rules=await prisma.financeRule.findMany({orderBy:{createdAt:"desc"},take:50});
 const common:WorkspaceField[]=[{name:"scope",label:"Scope",options:["DEFAULT","HOST","VEHICLE","CATEGORY"]},{name:"scopeId",label:"Scope ID (* for default)",value:"*"},{name:"effectiveAt",label:"Effective from",type:"datetime-local"},{name:"endsAt",label:"Promotion ends (optional)",type:"datetime-local",required:false},{name:"approve",label:"Business approval",options:actor.role==="SUPER_ADMIN"?["no","yes"]:["no"]},{name:"stepUpCode",label:"Fresh finance code for approval",required:false}];
 const definitions:Array<{kind:string;title:string;fields:WorkspaceField[]}>=[{kind:"COMMISSION",title:"Commission version",fields:[{name:"basisPoints",label:"Commission basis points (100 = 1%)",type:"number",min:0,max:10000,value:0},{name:"fixedCents",label:"Visible booking fee (USD)",type:"money",min:0,value:0},{name:"minimumCents",label:"Minimum commission (USD)",type:"money",min:0,value:0},{name:"maximumCents",label:"Maximum commission (USD)",type:"money",min:0,value:1000000},{name:"hostDiscountBps",label:"Host-funded discount share (basis points)",type:"number",min:0,max:10000,value:0}]},{kind:"TAX",title:"Jurisdiction tax version",fields:[{name:"rentalBps",label:"Rental tax basis points",type:"number",min:0,max:10000,value:0},{name:"feeBps",label:"Service fee tax basis points",type:"number",min:0,max:10000,value:0},{name:"extrasTaxable",label:"Extras taxable",options:["yes","no"]},{name:"exemptionsAllowed",label:"Evidence-backed exemptions permitted",options:["no","yes"]}]},{kind:"PAYOUT",title:"Settlement policy version",fields:[{name:"delayDays",label:"Settlement delay (days)",type:"number",min:0,max:365,value:7},{name:"minimumCents",label:"Minimum payout (USD)",type:"money",min:0.01,value:1},{name:"timezone",label:"IANA time zone",value:"America/Chicago"},{name:"hostMaySelect",label:"Host may select approved schedule",options:["no","yes"]}]},{kind:"LOSS",title:"Loss allocation version",fields:[{name:"refundHostBps",label:"Host share of proportional refund (basis points)",type:"number",min:0,max:10000,value:0},{name:"chargebackHostBps",label:"Host share of chargeback (basis points)",type:"number",min:0,max:10000,value:0},{name:"reverseTransfers",label:"Permit approved refund transfer recovery",options:["no","yes"]}]}];
 return <FinanceWorkspace admin title="Commission & tax configuration" description="Every change creates a version. Existing financial snapshots remain unchanged. Draft defaults require business approval."><p className="rounded-xl border border-amber-300/40 p-5 font-semibold text-amber-200">NOT TAX-APPROVED — PROFESSIONAL REVIEW REQUIRED</p>{actor.role==="SUPER_ADMIN"&&<Panel title="Approval verification"><ActionForm endpoint="/api/finance" action="stepUp" label="Send finance verification code"/></Panel>}{actor.role!=="FINANCE_AGENT"&&<div className="grid items-start gap-6 lg:grid-cols-2">{definitions.map(d=><Panel key={d.kind} title={d.title}><ActionForm endpoint="/api/finance" action="rule" values={{kind:d.kind}} fields={[...(d.kind==="TAX"?common.map(f=>f.name==="scope"?{...f,options:["JURISDICTION"]}:f.name==="scopeId"?{...f,label:"Exact vehicle location / jurisdiction",value:""}:f):common),...d.fields]} label="Create immutable rule version"/></Panel>)}</div>}<Panel title="Version history"><div className="space-y-4">{rules.length?rules.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 p-4"><div className="min-w-0"><p className="text-white">{r.kind} · version {r.version}</p><p className="break-all text-sm text-silver">{r.scope}: {r.scopeId} · effective {r.effectiveAt.toISOString()}</p></div><FinanceStatus value={r.approvedAt?"BUSINESS_APPROVED":"DRAFT"}/></div>):<p className="text-silver">No business-approved rules. Host payouts remain blocked until all required policies are approved.</p>}</div></Panel></FinanceWorkspace>;
}
